### ISSUE TITLE
Tortoise classifier false positives for copy-synthesis

### ISSUE THREAD

**Issue by brentspell** [neonbjb/tortoise-tts#101]
Thanks so much for sharing your work, Tortoise is an outstanding accomplishment in text-to-speech.

I have been playing around a bit with the classifier, and I found that it reports almost 100% false positives for ground truth audio that is round-tripped through the UnivNet vocoder. I'm guessing that the classifier is picking up on noise/artifacts from the vocoder and using that to misidentify the examples as coming from the Tortoise system. I don't have another UnivNet-based synthesizer handy, but the classifier might also detect synthetic speech from other systems that use the same pretrained vocoder as coming from Tortoise.

It might be possible to mitigate this by training the classifier using negatives generated by copy-synthesis of ground truth recordings.  Anyway, I thought I would pass these findings along in case they are of interest.

**Comment by neonbjb** [comment]
Hey Brent,
You got me. :)

The classifier was indeed trained to detect audio clips that have gone through a vocoder versus those that did not. This was the only computationally feasible way that I could think of to train it.

As you probably know, there are quite a few weaknesses with using this approach, which I'd rather not publicly disclose. Realistically, I think training truly robust classifiers like this are way outside of my (current) abilities. No matter what I build, it is pretty likely that an sufficiently motivated adversary could break it. My thought with providing the classifier is that it prevents (or diminishes) the risk of "lazy abuse" where someone with no ML knowledge comes in, runs a few scripts and tries to impersonate a politician, for example.

I'm closing this to reduce it's visibility, but I am happy to continue chatting with you about it. Hopefully you don't mind.

**Comment by brentspell** [comment]
No problem! I think the classifier idea is a super interesting, and having worked on other audio-based watermarking schemes, I was curious as to how it worked. Thanks for the notes!
