### ISSUE TITLE
VRAM amount

### ISSUE THREAD

**Issue by NikitaKononov** [neonbjb/tortoise-tts#109]
Hello! Amazing work, thanks a lot for sharing
How much VRAM is required to inference the model?
Will such GPU's as 1660ti (6 gb VRAM) or 1080 (8gb VRAM) be able to run inference?

**Comment by neonbjb** [comment]
Someone earlier commented that they were able to get 6GB to work. I have not personally tested this. All my GPUs have 24GB of memory. :(
