### ISSUE TITLE
Keeping the last hidden layer instead of reproducing it

### ISSUE THREAD

**Issue by monophthongal** [neonbjb/tortoise-tts#116]
Hi,

I'm interested in exploring the more efficient option suggested by this comment in api.py:

```
# The diffusion model actually wants the last hidden layer from the autoregressive model as conditioning
# inputs. Re-produce those for the top results. This could be made more efficient by storing all of these
# results, but will increase memory usage.
```

I saved the output of this step to a file for a 20-word sentence, and it was only ~5 MB per sample, which seems fine.

I was wondering if you had any suggestions for where to start on this? From what I can tell, this step invokes the autoregressive model in a different way from `inference_speech()`, and does some transformations on the output in `get_logits()`.

Would it be possible to extract the exact same values from the output of `inference_model.generate()` inside `inference_speech()` instead?

Thanks for any help!

**Comment by neonbjb** [comment]
Hey there. Yes you're on the right track. You can indeed extract these hidden states from `inference_model.generate()`. I believe the option you want to specify is `output_hidden_states=True` from https://huggingface.co/docs/transformers/v4.20.1/en/main_classes/text_generation#transformers.generation_utils.GenerationMixin.generate.

Full disclosure: I've done some benchmarking on the computational cost of doing this extra forward pass, and it is pretty minor. Like ~20ms on a V100 equivalent for a medium size sentence. So don't expect this to provide a huge performance boost.

**Comment by monophthongal** [comment]
OK thanks for the link - I'll give it a try.

I've actually been looking into ways to speed up inference on CPU. This step takes around ~5 seconds for a long sentence, so it becomes more of a bottleneck than it is with a GPU.

**Comment by neonbjb** [comment]
Ah yeah. If you're doing it on a CPU, every single FLOP counts.
