### ISSUE TITLE
Support other languages?

### ISSUE THREAD

**Issue by xinkez** [neonbjb/tortoise-tts#118]
Hi,

Does tortoise-tts support other languages? for example, Korean, Chinese

Thanks.

**Comment by jnordberg** [comment]
Not the released checkpoints, but the architecture could support it, see #5

**Comment by xinkez** [comment]
> Not the released checkpoints, but the architecture could support it, see #5

Got it. Thank you. I will close this issue.

**Comment by neonbjb** [comment]
There are people working on chinese and russian versions, though i haven't spoken to them in awhile. I am happy to support anyone training a model for another language if they commit to open sourcing it.
