### ISSUE TITLE
Customizing pronunciation

### ISSUE THREAD

**Issue by monophthongal** [neonbjb/tortoise-tts#12]
I was wondering if you had any suggestions for making TorToiSe pronounce words in a specific way, for example, for fictional names or domain-specific terms that it's not familiar with?

I've had pretty good luck with word replacement - programmatically replacing words with phonetic spellings - though with unusual fictional names it sometimes it puts emphasis on the wrong syllable.

Thanks for any suggestions - and fantastic work on this project!

**Comment by neonbjb** [comment]
That's a really tough one. The only thing I can suggest is:
1. Install [ocotillo](https://github.com/neonbjb/ocotillo) (which was used to transcribe ~90% of the training set for Tortoise)
2. Record yourself speaking the word or sentence you are interested in.
3. Feed the clip through ocotillo and see how it interprets the word.
4. Replace that word with the given transcription.

To be frank, though - my guess is that these words are simply getting transcribed incorrectly and therefore Tortoise never really learned how to pronounce them. I don't really have any ideas for how to fix this situation. I'm certainly open to suggestions.

**Comment by neonbjb** [comment]
Going to close this, but I am a little curious if it helped at all.
