### ISSUE TITLE
Russian model ToiTorSe

### ISSUE THREAD

**Issue by dreamfaceprod** [neonbjb/tortoise-tts#120]
Hi, Dear James!          
My name is Vladimir, I am the CEO of the "DreamFace" team, we are engaged in video production using neural networks. We would like to discuss the possibility of creating a Tortoise model for the Russian language.

So, is it possible to start such a discussion and how much would it cost approximately?

**Comment by neonbjb** [comment]
Hey Vladimir,
I cannot train a new language, but I am happy to answer the questions of your engineering staff if they want to try to build their own.

**Comment by dreamfaceprod** [comment]
> Привет, Владимир, я не могу обучить новый язык, но я с радостью отвечу на вопросы вашего инженерного персонала, если они захотят попробовать создать свой собственный.
Hey James!
we have achieved some results, but so far they are far from good.
can we consult you?

**Comment by dreamfaceprod** [comment]
Hey James!
we have achieved some results, but so far they are far from good.
can we consult you?

**Comment by neonbjb** [comment]
Sure, let me know what questions you have. Would prefer to keep communication open so the rest of the community could benefit.

**Comment by SaadBazaz** [comment]
Any results?
