### ISSUE TITLE
Fix for longer sentence

### ISSUE THREAD

**Issue by Rishv123** [neonbjb/tortoise-tts#136]
Hi, this tts model is absolutely phenomenal!! 
Just one question, I am a beginner and just getting started with programming.
I can use this model in Google colab but output gets stuck in 23 second limit.

I read on the page that
(Tools for using larger text
.. "textfile-- <....>" ..)
How do you use this in Google colab, means do I replace the (text = "...." ) in the colab window with this?

Sorry if the question is too stupid.

**Comment by neonbjb** [comment]
You can run commands in colab by prepending them with `!`. I'd recommend doing something like `!run python read.py ....`. Will probably take some tinkering but I know it works.
