### ISSUE TITLE
how do i use conditioning latents?

### ISSUE THREAD

**Issue by princes21** [neonbjb/tortoise-tts#137]
so I'm following the instructions, i made a folder for the files, they are .wav 22050 sample rate, and 32-bit float but i get the following:
C:\Users\user\tortoise-tts\tortoise>python get_conditioning_latents.py --voice=myfolder
Traceback (most recent call last):
  File "C:\Users\user\tortoise-tts\tortoise\get_conditioning_latents.py", line 23, in <module>
    cond_paths = voices[voice]
KeyError: 'myfolder'

I tried it with an existing, provided folder. It worked fine. So i tried replacing the original files with mine, but executing the command, the voice generated is based off of the files that I replaced. 

If that matters, I'm trying to generate a conditioning latent of a randomly generated voice

the folder i made changes in was tortoise-tts/tortoise/voices

**Comment by AriDeve** [comment]
Have  you resolved this?
