### ISSUE TITLE
Problems running the program. (Failed to import soundfile)

### ISSUE THREAD

**Issue by NakoloshGoodsby** [neonbjb/tortoise-tts#148]
I've had a lot of trouble trying to get this to work, I have some experience running programs like this through anaconda prompt but for some reason I can't get this to work. This is the error I have currently. I've installed all the listed dependencies and have a feeling I'm missing something very obvious, if anyone can help me I would really appreciate it. My OS is windows 11.

(base) C:\Users\Mok\anaconda3\envs\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "C:\Users\Mok\anaconda3\envs\tortoise-tts\tortoise\do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "C:\Users\Mok\anaconda3\envs\tortoise-tts\tortoise\api.py", line 242, in __init__
    self.clvp.load_state_dict(torch.load(get_model_path('clvp2.pth', models_dir)))
  File "C:\Users\Mok\anaconda3\lib\site-packages\torch\serialization.py", line 705, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "C:\Users\Mok\anaconda3\lib\site-packages\torch\serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by NakoloshGoodsby** [comment]
I think I fixed that previous error. I believe I was not activating the environment when installing something. I'm now getting this error. I've followed all the instructions without success and cleanly reinstalled anaconda and everything included multiple times now.

(tortoise-tts) C:\Users\Mok\anaconda3\envs\tortoise-tts>python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "C:\Users\Mok\anaconda3\envs\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\Users\Mok\anaconda3\envs\tortoise-tts\tortoise\api.py", line 9, in <module>
    import progressbar
ModuleNotFoundError: No module named 'progressbar'

**Comment by NakoloshGoodsby** [comment]
Sorry about the constant edits and the change of the title. I've fixed a few of the many problems I've had myself and wanted to update this if anyone reads any of this.

**Comment by neonbjb** [comment]
The first error sounds like you may have some corrupted model files. These won't self correct, so you'll have to remove your bad files and re-download. Delete *.pth in `C:\Users\<yourname>\.cache\tortoise-tts`.

I dont know about the second error. It sounds like a dependency issue with progressbar.

**Comment by NakoloshGoodsby** [comment]
> The first error sounds like you may have some corrupted model files. These won't self correct, so you'll have to remove your bad files and re-download. Delete *.pth in `C:\Users\<yourname>\.cache\tortoise-tts`.
> 
> I dont know about the second error. It sounds like a dependency issue with progressbar.

Thanks so much for the reply, I've run into this same problem with corrupted files every time I've downloaded tortoise not matter what I do. I was reading that conda downloads are especially sensitive to internet disruptions and I get constant HTTP errors stopping my downloads when I go to install the dependencies for tortoise. I tried using a VPN to download the dependencies and this actually completed the downloads. I've had problems with my internet connection recently and assumed that if nothing I do fixes this, that it must be my own connection. I'm not very experienced with this kind of stuff and I don't mean to offend, but could this be a problem with the downloads themselves?

**Comment by neonbjb** [comment]
Hey there,
Probably not an issue with the website, I'm using Huggingface's site to host the models and they have deployment down pretty well.

If you want, you can try to down them manually from here:
https://huggingface.co/jbetker/tortoise-tts-v2/tree/main/models

**Comment by NakoloshGoodsby** [comment]
> Hey there, Probably not an issue with the website, I'm using Huggingface's site to host the models and they have deployment down pretty well.
> 
> If you want, you can try to down them manually from here: https://huggingface.co/jbetker/tortoise-tts-v2/tree/main/models

The models I had were different in size, that might be part of the problem. I'm still running into the progress bar problem though. I was also missing other files so I think this is just a problem with my internet and conda being more sensitive to interruptions than I knew.

**Comment by NakoloshGoodsby** [comment]
> Hey there, Probably not an issue with the website, I'm using Huggingface's site to host the models and they have deployment down pretty well.
> 
> If you want, you can try to down them manually from here: https://huggingface.co/jbetker/tortoise-tts-v2/tree/main/models

Thanks for taking the time to help me a bit neon, with all the trouble i'm having helping me is pretty much charity. I have a 3080 and windows 11 if that means anything here.
I git cloned
git clone https://huggingface.co/jbetker/tortoise-tts-v2

from what you linked here https://huggingface.co/jbetker/tortoise-tts-v2 

and It works now for the dotts.py script but the read.py script returns 
(tortoise-tts) D:\Tests\All\Tortoise\tortoise-tts-v2>python tortoise/read.py --textfile <your text to be read> --voice random
The system cannot find the file specified.
I think I'm missing something even more obvious on this one, a pathing issue.

**Comment by NakoloshGoodsby** [comment]
> Hey there, Probably not an issue with the website, I'm using Huggingface's site to host the models and they have deployment down pretty well.
> 
> If you want, you can try to down them manually from here: https://huggingface.co/jbetker/tortoise-tts-v2/tree/main/models

Thanks for all the help so far, I just git cloned the tortoise-v2 from that link and that seemed to get it working for the most part, only error I have now is "python tortoise/read.py --textfile <your text to be read> --voice random" returns an The system cannot find the file specified. Despite being in the same folder and this just being a regular pathing error I think, I can't figure out what is wrong.

**Comment by cgcsw02** [comment]
> > Hey there, Probably not an issue with the website, I'm using Huggingface's site to host the models and they have deployment down pretty well.
> > If you want, you can try to down them manually from here: https://huggingface.co/jbetker/tortoise-tts-v2/tree/main/models
> 
> Thanks for all the help so far, I just git cloned the tortoise-v2 from that link and that seemed to get it working for the most part, only error I have now is "python tortoise/read.py --textfile --voice random" returns an The system cannot find the file specified. Despite being in the same folder and this just being a regular pathing error I think, I can't figure out what is wrong.

what i can do for this "error I have now is "python tortoise/read.py --textfile --voice random" returns an The system cannot find the file specified. Despite being in the same folder"

**Comment by NakoloshGoodsby** [comment]
> what i can do for this "error I have now is "python tortoise/read.py --textfile --voice random" returns an The system cannot find the file specified. Despite being in the same folder"

I wasn't sure either, I worked around that by editing the file riding_hood.txt in the data folder to say my text. I use this command to read it. 

python tortoise/read.py --voice=random --textfile=tortoise/data/riding_hood.txt --preset= fast

**Comment by AhmedBlender** [comment]
Hi brother
I'm used blender 3.3.3lts. this program it is not import in my addons. Why?
Thank you for help me brother
