### ISSUE TITLE
Does the model support other languages?

### ISSUE THREAD

**Issue by jmmaa** [neonbjb/tortoise-tts#149]
Just curious about this project, but I was wondering if it can also integrate to other languages like chinese, japanese, etc.

**Comment by akshhack** [comment]
@jmmaa wanna collaborate on building that together? If so, write me at akshatp.cs@gmail.com -- I'm a CMU AI grad with tremendous interest in this space. Always looking for cool people to work with.

**Comment by neonbjb** [comment]
It does not support other languages, but the techniques used to build it are general and could extend to other languages if someone had a dataset big enough and the compute/time to train it.

There are a couple of people interested in this @akshhack, try looking around in some of the other issues or discussions if @jmmaa doesn't get back to you.

In general, I would be happy to support anyone training a version of Tortoise for another language provided they will commit to open sourcing the inference models like I did with English.

**Comment by akshhack** [comment]
@neonbjb I'd be happy to sign and open source my work. I really want to democratize access to this brilliant technology in my mother tongue Hindi. Of course, I'm clearly light years away from such sophisticated work, but I'd love to take your help in getting something started. Thank you. 

What's the best place for me to reach out to you? jbetker@gmail.com?

**Comment by neonbjb** [comment]
Hey there,
Yeah, sure - feel free to reach out. To be clear, I don't really have the time to do much hand-holding, but I can definitely provide high-level guidance and answer blocking questions as you work on this. The first step will be gathering a dataset for your target language and figuring out how to transcribe it. Looks like there is [a wav2vec for Hindi](https://huggingface.co/theainerd/Wav2Vec2-large-xlsr-hindi) so your first step might be integrating that with [ocotillo](https://github.com/neonbjb/ocotillo) and doing some experiments to see what kind of quality the transcriptions are.

**Comment by mathigatti** [comment]
wouldn't it be possible to use a multispeak wav2vec and a phonetic representation of text (like IPA or [whatever](https://pypi.org/project/phonemizer/)) to make it work on any language all at once?
