### ISSUE TITLE
Tone Classifier

### ISSUE THREAD

**Issue by honestabelink** [neonbjb/tortoise-tts#15]
Github : https://github.com/bfelbo/deepmoji
Demo : https://deepmoji.mit.edu/

![image](https://user-images.githubusercontent.com/6005775/166069307-8876a933-bc98-409c-8c02-9d54861b279a.png)

The embedding from this would be useful to condition the model for intonation. ~~In the meantime, this could be integrated cheaply along side the CVLP step, so we'd have similarity measure between text, speech, and tone.~~

Edit. Nvm I got too excite about the cheep integration, the model only excepts text tokens as input.

**Comment by neonbjb** [comment]
This is a cool idea, but I don't think I will be implementing it.
