### ISSUE TITLE
Issue reading text files?

### ISSUE THREAD

**Issue by Delcos** [neonbjb/tortoise-tts#156]
I may be missing something, but can I get a confirmation on the location the txt file needs to be, because it can't seem to find it.

**Comment by neonbjb** [comment]
Assuming you mean the text file for `read.py`, it needs to be in the current working directory where you are running the script.

**Comment by fitbyprabhat** [comment]
Hey, is it possible to Create a .ipyb file for Testing how things can Work in googe Collab for Read.py. I am trying it for a Long Time. It would be nice if it is possible.

**Comment by neonbjb** [comment]
There is an ipynb file in this repo for exactly that.

**Comment by fitbyprabhat** [comment]
I can't believe for real that you actually replied 💕. And i am sure I am the only your biggest fan.

**Comment by neonbjb** [comment]
Yeah - apologies. I'm quite busy these days and a frustrating number of folks post questions and issues that have already been opened elsewhere.
