### ISSUE TITLE
Tortoise as an Android TTS server

### ISSUE THREAD

**Issue by starsforeveryone** [neonbjb/tortoise-tts#163]
Dear developers,

I'm amazed by the quality of your sound examples. Sadly, I'm no programmer, therefore the suggestion I'm going to make in this thread would have to be implemented by someone else. Anyway, I still wanted to suggest it because I believe it would be beneficial to both the users and the project, even far further than that, to all of Android.

For those of us who like FOSS (free and open source software) and want to ditch Google altogether, there is an excellent alternative to Google Maps out there: OsmAnd~ (https://f-droid.org/packages/net.osmand.plus/) It can do almost everything Google Maps can do, including TTS navigational directions, of course.

Sadly, the TTS output lacks a modern TTS server. The only solution as of now would be eSpeak, which sounds a lot less appealing. If we want FOSS to succeed, we need to be able to offer modern solutions that can compete with those proprietary solutions offered by the big tech companies. Text-to-Speech is an important example of this, since noone wants to listen to a robot-like voice that reminds the user of an old car navi device from the early 2000's. So we lack an amazing FOSS solution for TTS. This is true for all of Android, since the regular TTS server is a proprietary Google App.

Would it be possible to modify Tortoise to act as an Android TTS server, release an APK, and upload it to the popular F-Droid store? That would help the free software world a lot. I would be willing to help test it, of course! 🫡

Kind regards

**Comment by neonbjb** [comment]
Hey there, that'd be cool and maybe we'll get there with a few more cycles of Moore's law but for now tortoise is simply too slow for any kind of live tts. You'd be much better served by open source implementations of fast speech (which should run on phones) or tacotron2.

With some engineering you could probably pre render a bunch of voices for nav, but that's even further from where I specialize.

Good luck!
