### ISSUE TITLE
Wrong accent result

### ISSUE THREAD

**Issue by luciasalle** [neonbjb/tortoise-tts#166]
Hi! I have been using Tortoise for a project and getting amazing results.

However, with a specific subject I am getting a British accent instead of an American one. Do you know why this might be happening and how I can solve it? 

This also brings me to the question of whether it is possible to get non British or American accents, and get as output other accents like Indian, Australian or even non-English accents (French, Spanish, etc.)

Awesome project and awesome results, possibly the best ones I have seen. Congrats!

**Comment by neonbjb** [comment]
Hey there,
A few others have commented on this phenomenon. I can't say for sure, but I think what the is happening is that the model has learned to cluster certain types of voices by properties that are completely unrelated to the voice themselves (for example, background noise, the recording hardware used, or maybe even the way that words are spoken). If your reference voices have these properties, they get thrown in a bin with a voice that sounds nothing like the target.

In general, I don't think people have had much success in fixing this, but the one advice I would offer for you to try is to use try a few different reference clips.

Thanks!

**Comment by luciasalle** [comment]
Thanks so much for your response!
