### ISSUE TITLE
Question about adding a new voice.

### ISSUE THREAD

**Issue by NakoloshGoodsby** [neonbjb/tortoise-tts#168]
I assume this is another very basic question so sorry for this. How exactly do I perform step 6 on the guide to adding a new voice? I have a folder called "utils" in my main directory that has six different .py files and I haven't tried in a while but running them individually through anaconda prompt wasn't working for me.  

The step I'm referring to: "Run tortoise utilities with --voice=<your_subdirectory_name>."

**Comment by tueksta** [comment]
there is one line that says:
```python
custom_voice_folder = f"tortoise/voices/{CUSTOM_VOICE_NAME}"
```
meaning you can create a new subfolder in `tortoise/voices` give it a name you like and put .wav files or .mp3 inside it. I recommend using the colab project to learn how this works, as it reads pretty well and explains each step.

**Comment by NakoloshGoodsby** [comment]
> there is one line that says:
> 
> ```python
> custom_voice_folder = f"tortoise/voices/{CUSTOM_VOICE_NAME}"
> ```
> 
> meaning you can create a new subfolder in `tortoise/voices` give it a name you like and put .wav files or .mp3 inside it. I recommend using the colab project to learn how this works, as it reads pretty well and explains each step.

Thanks for the reply. I understand the beginning part fine. I've added what files needed to be added. I was asking what exactly am I running for step 6 when it mentions the utilities folder. I have a folder named util that has multiple python scripts inside. I might need to do as you suggested and try the colab, but Id really like to know what needed to be done locally.

**Comment by tueksta** [comment]
I think he meant to just run python `tortoise/do_tts.py --text "<yourtext>" --voice <yourvoicefolder> --preset fast`. do_tts will use the utilities.

**Comment by NakoloshGoodsby** [comment]
> I think he meant to just run python `tortoise/do_tts.py --text "<yourtext>" --voice <yourvoicefolder> --preset fast`. do_tts will use the utilities.

Ah, Thanks again for the answer. I will leave this up for a day or so for other answers but that's probably correct.
