### ISSUE TITLE
Static modulation output

### ISSUE THREAD

**Issue by rebotnix** [neonbjb/tortoise-tts#171]
Hi, 

I am very impressed with this project. I have been working with Tacatron2 for the last 5 years with Hifigan to create text to speech. Most of the time it took me over 100 hours for a single good voice and it was not possible to have a transfer learning with only 3 audio samples of 10 seconds length. 

I recompile pytorch on an edge ARM device with 2048 cores and 64 GB (NVIDIA Jetson Orin) and inference works really nice on this low energy device and i generate a voice with just 4 samples 6-10 seconds long.

I use api to generate the output and would I saw that each output is different from each other. The modulation is completely different each time.  Can I set the parameters for a static output?

I start with this simple API demo snipset. Hope for understanding that this is my first try with this new type of synthetic text to speech generation. Thanks a lot. 

```
import torch
import torchaudio
import torch.nn as nn
import torch.nn.functional as F

from tortoise.api import TextToSpeech
from tortoise.utils.audio import load_audio, load_voice, load_voices

tts = TextToSpeech()
text = "What would happen if we combined them all?"

preset = "high_quality"
voice = 'female1'
voice_samples, conditioning_latents = load_voice(voice)
gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
                          preset=preset)
torchaudio.save('generated.wav', gen.squeeze(0).cpu(), 24000)
```

**Comment by neonbjb** [comment]
You should be able to get deterministic outputs by setting the `use_deterministic_seed=` parameter, but too be honest, I haven't tested this in awhile. Let me know if that works.

**Comment by rebotnix** [comment]
Hi @neonbjb , thanks for your response, i will try use_determisnistic_seed and share some results. Is there a discord group for diskussion? 

I was so excited to understand that it is possible to use Dall-E based models for TTS. So i tested also some german corpus as input and generate english spoken words, and it works. You can do great things with this technology. When I think about e-learning for schools alone, employee videos or robots that don't beep but speak in their favorite language, we're talking about a very creative process, not the shitty deep fakes topic. 

Please allow some questions:
I have access to 2 DBX machines and i would like to see if i can train corpus of 5000 hours german context. 

Do i have to train each pytorch *.pth model that is defined in the api.py (the ones that i downloaded from hugginface)? 
Is there a train example how i can train a model(s) from scratch?
