### ISSUE TITLE
2GB GPU memory issues

### ISSUE THREAD

**Issue by Sewlell** [neonbjb/tortoise-tts#181]
So here's the problem:

I have issues with the **CUDA out of memory**, so I change the autoregressive_batch_size from None into 0.9 ( I couldn't run in 1 as well the **CUDA out of memory error** still appeared by 100MB differences )

And then it run into **'float' object cannot be interpreted into integer**, so then I switch the autoregressive_batch_size back into 1 and it worked without showing **'float' object cannot be interpreted into integer**. Yes, the CUDA out of memory error still appeared and I still cannot have my exported audio with my custom voice. 

Is there any solution for this issues other than updating hardware and using CPU-only Pytorch?

Setup ( it is an upgraded laptop ):
Intel i5 10210U, 12GB RAM with integrated graphics and NVIDIA MX130

**Comment by neonbjb** [comment]
1 is the smallest batch size you can do. I don't think you'll be able to run tortoise on 2gb of gpu memory without some crazy tricks, I'd recommend using collab in this case.
