### ISSUE TITLE
Transformers version needs to be 4.19, or else I get errors

### ISSUE THREAD

**Issue by jstephencorey** [neonbjb/tortoise-tts#186]
I ran tortoise yesterday and it worked fine, but when I ran it today it would reset my google colab whenever I tried to import from tortoise.api. I dug into it a bit and I think the issue has to do with a newer version of transformers, if I just added the line `!pip install transformers==4.19` before the line `!pip3 install -r requirements.txt`, it worked fine. 

I don't know the exact reasons, but I recommend at the very least changing the requirements.txt to have transformers==4.19 instead of transformers>=4.19

**Comment by fitbyprabhat** [comment]
✨ thanks
