### ISSUE TITLE
Unable to import Tortoise on Google Colab

### ISSUE THREAD

**Issue by JamesLefrere** [neonbjb/tortoise-tts#187]
When importing `TextToSpeech` on Google Colab, I'm encountering this error:

```src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f453d3c5d98```

Which crashes the runtime. The runtime type is GPU.

**Comment by fitbyprabhat** [comment]
The same issue I am getting anyone here for help? Is this community still alive?

**Comment by plowsjordan** [comment]
Hey @fitbyprabhat it appears that parts of the community are inactive.

**Comment by fitbyprabhat** [comment]
I got the solution if anyone wanna know let me know x😁

**Comment by plowsjordan** [comment]
@fitbyprabhat I actually run another AI startup but created a channel in our discord for this, if you are interested. I think that the work being done here can be replicated, partially open-sourced, with safety in place and community driven to support further applications. 

Let me know if you want to join

**Comment by fitbyprabhat** [comment]
Would love to.

**Comment by plowsjordan** [comment]
@fitbyprabhat It would be the early days but I think this entire community could come together and build this out in a meaningful way that could still implement safety in a positive way. Going slow will be critical 

https://discord.gg/aksp6W3t2c

**Comment by fitbyprabhat** [comment]
> When importing `TextToSpeech` on Google Colab, I'm encountering this error:
> 
> ```src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f453d3c5d98```
> 
> Which crashes the runtime. The runtime type is GPU. 

#By the way

 Add transformer of lower version before installing requirements and that will work

**Comment by neonbjb** [comment]
Thanks @fitbyprabhat, I've updated the colab with your fix. Gotta love python deps.
