### ISSUE TITLE
add web demo to Huggingface 

### ISSUE THREAD

**Issue by AK391** [neonbjb/tortoise-tts#2]
Hi, would you be interested in adding tortoise-tts web demo to Hugging Face using Gradio? I see there is already models setup on Huggingface for this repo https://huggingface.co/jbetker

here is a guide for adding spaces to your org or username

How to add a Space: https://huggingface.co/blog/gradio-spaces

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

a Gradio Demo can be setup in 2 lines of code using the inference api (if enabled) integration through huggingface

```python
import gradio as gr
gr.Interface.load("huggingface/jbetker/tortoise-tts-v2").launch()
```

would launch the demo

Please let us know if you would be interested and if you have any questions.

**Comment by neonbjb** [comment]
I'd love to do this, but this model will not run on CPUs (inference will take hours or more). I read that GPU runtimes are for organizations only. Let me know if this understanding is wrong..

**Comment by AK391** [comment]
@neonbjb great, from the spaces docs https://huggingface.co/docs/hub/spaces

"Each Spaces environment is limited to 16GB RAM and 8 CPU cores. Organization [subscribers](https://huggingface.co/pricing) (Lab, Startup, and Enterprise) can access Spaces with one T4 GPU on a case-by-case basis. Please email us at website at huggingface.co or let us know on [Twitter](https://twitter.com/huggingface) if you need one."

I can also send a request for GPU for a space once its setup

**Comment by neonbjb** [comment]
Awesome, I'd be glad to do this then! Expect something in the next day or two..

**Comment by osanseviero** [comment]
Hey there, if it's ok I would love to work on this. I'm actually half-way done through it :rocket:

**Comment by neonbjb** [comment]
Sure, have at it. I'll await your pr.

**Comment by osanseviero** [comment]
You can find a working demo in https://huggingface.co/spaces/osanseviero/tortoisse-tts :fire:

**Comment by neonbjb** [comment]
Hmm looks like it is running out of RAM? Did you get it to work without this error?

Tortoise shouldn't need more than 16GB of RAM, but this may be a result of doing the computations in on CPU. I'll have to profile it to be sure.

**Comment by osanseviero** [comment]
I restarted it and it's up again, but I haven't looked at why we got a out of RAM issue before.

**Comment by neonbjb** [comment]
Space created: https://huggingface.co/spaces/jbetker/tortoise; I'll contact website@ to see if I can get a GPU instance dedicated to it.

**Comment by neonbjb** [comment]
Closing this out.
