### ISSUE TITLE
Getting CUDA out of memory error in training VQVAE

### ISSUE THREAD

**Issue by jry-king** [neonbjb/tortoise-tts#200]
Hi there! This is a very nice work and it's really the first TTS model with such a great number of parameters to my knowledge. I also want to train my own VQVAE on my machines and I would like to ask some questions about it.

In README you mentioned that training was done on DLAS trainer, so I tried to use it to train a VQVAE model (https://github.com/neonbjb/DL-Art-School/blob/master/codes/models/audio/tts/lucidrains_dvae.py). I used 8 machines with 8 V100 on each machine, and the command I used is basically
`python -m torch.distributed.launch --nproc_per_node=8 --nnodes=8 --node_rank=$RANK --master_addr=$MASTER_ADDR --master_port=$MASTER_PORT codes/train.py -opt $CONFIG --launcher=pytorch`
And the configuration is as follows, with some modifications to fit my wenetspeech dataset

```name: train_vqvae \
model: extensibletrainer
scale: 1
gpu_ids: [0,1,2,3,4,5,6,7]
start_step: -1
checkpointing_enabled: false  # <-- Gradient checkpointing. Enable for huge GPU memory savings. Disable for distributed training.
fp16: false
wandb: false  # <-- enable to log to wandb. tensorboard logging is always enabled.
use_tb_logger: true

datasets:
train:
    name: wenet_train
    n_workers: 8
    batch_size: 8192
    mode: preprocessed_mel
    path: /data/wenet_data/shards
    cache_path: /data/wenet_data/shards/cache_path.pth
    should_squeeze: True
    num_mels: 80
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    fmin: 0
    fmax: 8000
  val:
    name: wenet_val
    n_workers: 8
    batch_size: 128
    mode: preprocessed_mel
    path: /data/wenet_data/shards/dev
    cache_path: /data/wenet_data/shards/dev/cache_path.pth
    should_squeeze: True
    num_mels: 80
    n_fft: 1024
    hop_size: 256
    win_size: 1024
    fmin: 0
    fmax: 8000

networks:
  generator:
    type: generator 
    which_model_G: lucidrains_dvae  
    kwargs:
      positional_dims: 1
      num_tokens: 8192
      codebook_dim: 256
      num_layers: 2
      num_resnet_blocks: 3
      hidden_dim: 512
      channels: 80
      kernel_size: 3
      use_transposed_convs: false

path:
  #pretrain_model_generator: <insert pretrained model path if desired>
  strict_load: true
  #resume_state: ../experiments/train_imgnet_vqvae_stage1/training_state/0.state   # <-- Set this to resume from a previous training state.

steps:        
  generator:
    training: generator
    optimizer_params: 
      lr: !!float 3e-4
      weight_decay: 0.01
    injectors: 
      # Cool hack for more training diversity:
      # Make sure to change below references to `hq` to `cropped`.
      #random_crop:
      #  train: true
      #  type: random_crop
      #  dim_in: 224
      #  dim_out: 192
      #  in: hq
      #  out: cropped
      gen_inj_train:
        train: true
        type: generator 
        generator: generator
        in: mel
        out: [recon, codebook_commitment_loss, gen]
    losses:
      recon_loss:
        type: pix
        criterion: l2
        weight: 1
        fake: gen
        real: mel
      commitment_loss:
        type: direct
        weight: .25
        key: codebook_commitment_loss

train:
  niter: 50000000 
  warmup_iter: -1
  mega_batch_factor: 2    # <-- Gradient accumulation factor. If you are running OOM, increase this to [2,4,8].
  val_freq: 4000

  default_lr_scheme: MultiStepLR
  gen_lr_steps: [50000, 100000, 140000, 180000]
  lr_gamma: 0.5

eval:
  output_state: gen
  injectors:
    gen_inj_eval:
      type: generator
      generator: generator
      in: hq
      out: [gen, codebook_commitment_loss]

logger:
  print_freq: 100
  save_checkpoint_freq: 1000
  visuals: [gen, mel]
  visual_debug_rate: 1000
  is_mel_spectrogram: true
```
Everything was fine in the first few steps, and the VRAM usage on each GPU was only about 5GB out of 32GB, but every time  when the training task reached the 1099th step it would raise OOM error on one of the machines and terminate all processes. Looks like there was some unexpected VRAM usage at that point, as shown in the dark purple line in the plot from Grafana
![image](https://user-images.githubusercontent.com/26543484/203262177-08083187-a053-48b2-b33a-1dfdf217ab4a.png)
By the way the initially raised error was something like "RuntimeError: NCCL communicator was aborted", and after inspecting logs on other machines I could always find something like "torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 11.13 GiB (GPU 6; 31.75 GiB total capacity; 19.26 GiB already allocated; 9.07 GiB free; 20.54 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF".

Maybe I should open this issue under DLAS repo but looks like the issues there is not very active. I could open another issue there if necessary. Any kind of help or suggestion is appreciated.

**Comment by neonbjb** [comment]
hmm that's an odd one. I can say that you should probably remove this, or it will crash at step 4000:
```
eval:
  output_state: gen
  injectors:
    gen_inj_eval:
      type: generator
      generator: generator
      in: hq
      out: [gen, codebook_commitment_loss]
```

The step you say it terminates on is pretty close to step 1000, when checkpoints are saved and the `visual_debug_rate` logic ticks over in your config. Maybe try setting `visual_debug_rate`, `save_checkpoint_freq` and `val_freq` to something really low like `5` and see if you can figure out which one (if any) are causing your issue.

**Comment by jry-king** [comment]
Thanks for your reply! I've done a few experiments on this, and here is the results:
- After changing `batch_size` from 8192 to 4096 the code crashed at step 2199.
- After changing `visual_debug_rate` and `save_checkpoint_freq` from 1000 to 10000000 the code still crashed at step 1099.
- Increasing `mega_batch_factor` didn't work.
- Using 2 machines instead of 8 and changing `batch_size` from 8192 to 2048 made the code crash at step 4433.
- Skipping the 1099th batch made the code crash at step 2945 (the 1153th step in the second epoch).
- Changing to another smaller dataset and run with 2 machines and `batch_size=2048` seemed to be OK (at least it survived 5600 steps, which is more than 300 epochs on that dataset).
The reason is still not very clear to me, but I suspect that it could be the size of the dataset being too large, or that I defined a dataset that reads wav files and convert them to mel spectrograms rather than reading mels directly from npz files, or some other data-related issues. Do you have any suggestions on how to locate the problem? Also, is there any special data loading schemes in DLAS framework? Thanks!

**Comment by jry-king** [comment]
After spending several days trying to find the problem in my codes, I decided to remove some of the data (especially those data used in epoch 0 step 1100), and then the code is running without OOM. Maybe it's just some data-related issue, and thanks for your help!

**Comment by meltingrock** [comment]
@jry-king Hi. 

I see that you have come quite far in getting to train tortoise on the Mandarin dataset, well done. I am trying to do the same with a South African language called Afrikaans. The language is very similar to Dutch (we are Dutch/Afrikaans speaking.)

Would you at all be willing to give me some advice on training Tortoise please. Your help will be greatly appreciated.

Thank you :-)
