### ISSUE TITLE
Question if if there is way to do A.wav to B.wav kind of transfer

### ISSUE THREAD

**Issue by gggrunt** [neonbjb/tortoise-tts#215]
I know there is a merge API, I am not sure if it does this.

I have some existing clips that are heavily accented and poor quality and I want to see if I can do A to B style transfer to improve them without losing all the unique features of accents. Would merging voice achieve such effect?

**Comment by neonbjb** [comment]
Probably not, but you should try it!

**Comment by gggrunt** [comment]
I guess I am wondering if there is a way to leverage tortoise to do audio clip to clip style transfer without the TTS. Currently I can STT first, collect other voice clips and then generate TTS...but that feels like a roundabout way to do this.

**Comment by tetmin** [comment]
> I guess I am wondering if there is a way to leverage tortoise to do audio clip to clip style transfer without the TTS. Currently I can STT first, collect other voice clips and then generate TTS...but that feels like a roundabout way to do this.

Hey, just wondering if you were still trying to do this? Happy to help out if so since we have been working on audio style transfer for a while. Happy to point you in the direction of OS or an API depending what you're trying to do.

**Comment by gggrunt** [comment]
@tetmin sure, yes, I am still looking for solutions for audio-to-audio so that we can generate more accented speech.  Do you guys have a discord where we can discuss further?

**Comment by tetmin** [comment]
> Do you guys have a discord where we can discuss further?

This is our Discord: https://discord.gg/c3tVKd6ebe

Alternatively feel free to DM on twitter (@tetmin) or ping Vatsal (https://twitter.com/vatsal_aggarwal).
