### ISSUE TITLE
Prompt engineering crashes Colab

### ISSUE THREAD

**Issue by jochemstoel** [neonbjb/tortoise-tts#216]
Trying to render the example string _[I am really sad,] Please feed me._ crashes Google Colab entirely. Putting anything beween [ and ] does.

**Comment by deathcloset** [comment]
WARNING | src/tcmalloc.cc:283] Attempt to free invalid pointer 0x7f5338702d98

Above is the runtime error in Google Colab for tortoise TTS when prompt engineering with square brackets in input string on generation:

I've unsuccessfully attempted many combinations of quotes, double quotes, triple comment quotes and escaping and not escaping the square brackets.

All attempts end with the tcmalloc error in Google Colab.

[I am really sad,] ;)

**Comment by neonbjb** [comment]
Hey guys - really sorry, but I will not be fixing this. This prompt engineering example was a fun experiment that ultimately didn't really do much. The best I can offer is "it works some of the time".

If it's something you really like or need, I urge you to dig into these bugs and submit a PR! I will gladly review.
