### ISSUE TITLE
Future support for Apple Silicon?

### ISSUE THREAD

**Issue by system1system2** [neonbjb/tortoise-tts#218]
The quality of this TTS system is impressive, @neonbjb. Thanks for sharing it with the community.

I read in the documentation that, to run it locally, you must have an NVIDIA GPU. Is there any chance you'll support M1/M2 chips in a future release?

**Comment by neonbjb** [comment]
Hey, thanks! I'm open to pull requests but am no longer actively developing this project.

**Comment by nicolabortignon** [comment]
hi @system1system2  would you be able to include the changes in the packages for future reference?

**Comment by noahlessard** [comment]
@nicolabortignon Any update on the mps idea? I am thinking of also trying to make the mps idea work and wondering what you found on it.

**Comment by Custos** [comment]
Quick note: some folks that may be having issues with instructions above installing tokenizer on a silicon map, install Rust:
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

**Comment by bananowysong** [comment]
Had the same issue.
Use the versions of packages stated in post.

The only difference is llvmlite.
conda install -c numba/label/dev llvmlite=0.40.0 will work.
You will ahve to install few packages that might miss and that should be all.

**Comment by bananowysong** [comment]
> pip install torch

Hey I managed to solve by using versions mentioned in the post (except conda install -c numba/label/dev llvmlite=0.40.0) and installing few other packages, but it seems to use CPU only to generate, it literaally takes like 10 minutes to gen few letters so not worth it.

**Comment by tedted23** [comment]
> I've yet to get this to work on my M1. Is there value in forking the fast version or Tortoise to concentrate efforts in one place to get it working on Apple Silicon hardware?

i modified the requierments.txt and followed  @system1system2  suggestion: 

requierments.txt:
tqdm
rotary_embedding_torch
transformers==4.19
tokenizers
inflect
progressbar
einops==0.4.1
unidecode
scipy==1.10.1
librosa==0.9.1
numba
ffmpeg
numpy==1.21.0
torchaudio
threadpoolctl
llvmlite
appdirs

**Comment by DrLLM23** [comment]
I have a macOS m1 (2020), with 16gb ram. I nearly got it running, but im getting the following error, perhaps someone can
point me in the right direction:
I also installed rust just to be on the safe side, but no luck!

    from .tokenizers import (ImportError: dlopen(/Users/a/anaconda3/envs/tortoise/lib/python3.11/site-packages/tokenizers-0.13.3-py3.11-macosx-11.1-arm64.egg/tokenizers/tokenizers.cpython-311-darwin.so, 0x0002): tried: '/Users/a/anaconda3/envs/tortoise/lib/python3.11/site-packages/tokenizers-0.13.3-py3.11-macosx-11.1-arm64.egg/tokenizers/tokenizers.cpython-311-darwin.so' (mach-o file, but is an incompatible architecture (have (x86_64), need (arm64e)))
