### ISSUE TITLE
Dokering

### ISSUE THREAD

**Issue by ErcinDedeoglu** [neonbjb/tortoise-tts#231]
Hello,
First of all, thank you for your fantastic work. I checked your Reddit answers too. Your hard work impressed me a lot.

My question is (before trying), why we can't have a docker version of it to avoid environmental issues?

**Comment by neonbjb** [comment]
No good reason for that. I'm simply not experienced in writing dockerfiles. If you build such an image, please file a PR so we can add it to the repo!

**Comment by ilyakam** [comment]
[Hope this helps](https://github.com/ilyakam/tortoise-tts)! TL;DR, I forked the repo, added a `Dockerfile` to it, and created [a new image](https://hub.docker.com/repository/docker/ilyakam/deps-for-tts/general) that includes the necessary, pre-cached models. If you're interested, you may want to check out a longer post on this topic -- [_Deploying AI to the Cloud_](https://academy.ilyakam.com/deploying-ai-to-the-cloud-3759d04df679).

**Comment by neonbjb** [comment]
Hey Ilya - nice work. If your changes aren't too intensive, please feel free to submit a PR for your fork. I'd be happy to incorporate something like this back into the repo.
