### ISSUE TITLE
Is It possible to use GPU on this?

### ISSUE THREAD

**Issue by arkilis** [neonbjb/tortoise-tts#243]
I tried the
```python
torchaudio.save('generated.wav', gen.squeeze(0).gpu(), 24000)
```
but doesn't work.

Many thanks!

**Comment by mb-alex-b-c** [comment]
Trying to answer your question as a newbie here, 
```
# Load it and send it through Tortoise.
voice_samples, conditioning_latents = load_voice(voice)
gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents, 
                          preset=preset)
torchaudio.save('generated.wav', gen.squeeze(0).cpu(), 24000)
IPython.display.Audio('generated.wav')
```

I think that step is just saving generated as a `wav` file. 
The most of computation intensive part is already done. 
Using GPU, instead of CPU, it may not give too much benefit here. 

This is just my amateur guess.

**Comment by arkilis** [comment]
@mb-alex-b-c  thank you for your help. Any idea how to speed up the process here? I am using 3080 Ti locally. But observe that GPU workload is just 1%-2% all the time.

**Comment by mb-alex-b-c** [comment]
One thing, which I may have corrected myself. 
```
torchaudio.save('generated.wav', gen.squeeze(0).cpu(), 24000)
```

`gen` is likely a tensor result from Pytorch. It performs a "squeeze" operation on the Tensor. 
Then, the squeeze result is made available from GPU to CPU, which will be further saved as 'generated.wav'. 
That means, `.cpu()` is actually needed, while `gpu()` should not be used at this operation at all.

**Comment by arkilis** [comment]
Thanks again for your help. But I do need to run this locally, perhaps with support on GPU.

**Comment by Fictiverse** [comment]
I made a env.yml to install the right packages

https://github.com/Fictiverse/tortoise-tts-Windows/blob/main/environment.yml

**Comment by arkilis** [comment]
@Fictiverse  Thanks, sorted it out now!
