### ISSUE TITLE
clvp in other models

### ISSUE THREAD

**Issue by Nikuson123** [neonbjb/tortoise-tts#25]
Can I use clvp in other models by just substituting it instead of clip?

**Comment by neonbjb** [comment]
Hey, not sure what you mean. CLVP is a contrastive model that pairs speech with text, while clip pairs images and text.

**Comment by Nikuson123** [comment]
That's what I need, just can I use it in other models and how will it be limited by the license?

**Comment by neonbjb** [comment]
Tortoise is Apache licensed, there are no limitations or restrictions. Feel free to use it however you'd like. Check back in a week or so, I will be deploying a bigger & better CLVP model soon.
