### ISSUE TITLE
AssertionError: Something went wrong with the alignment algorithm. 

### ISSUE THREAD

**Issue by AdityaPunetha** [neonbjb/tortoise-tts#269]
I've dumped a file, 'alignment_debug.pth' toyour current working directory. Please report this along with the file so it can get fixed.
https://github.com/AdityaPunetha/AdityaPunetha/blob/main/assets/alignment_debug.pth

**Comment by gedefet** [comment]
got the same error. any updates?

Thanks!

**Comment by neonbjb** [comment]
Hey, thanks for submitting this. I've gotten a few of these now that I don't have a real fix for, unfortunately. I think it's safe to call this feature "broken". :(
