### ISSUE TITLE
Training Script

### ISSUE THREAD

**Issue by lirus7** [neonbjb/tortoise-tts#27]
Hey!
Do you have any plans for sharing the training scripts?
PS: I wanted to check the performance on different languages.

**Comment by neonbjb** [comment]
I have not released training details.

**Comment by neonbjb** [comment]
I will probably be releasing training details in a paper in the coming months.

All models were trained in my own personal environment, which is open source: https://github.com/neonbjb/DL-Art-School.

What is missing is the training configs, which I do not plan to release. There's nothing too special here anyways. If you're capable of gathering the data and compute required, you probably have sufficient motivation and education to figure out how to train these models.

**Comment by dreamfaceprod** [comment]
Hi, Dear James!          
My name is Vladimir, I am the CEO of the "DreamFace" team, we are engaged in video production using neural networks. We would like to discuss the possibility of creating a Tortoise model for the Russian language.

So, is it possible to start such a discussion and how much would it cost approximately?
