### ISSUE TITLE
No module named 'tortoise.models.diffusion_decoder' / 'tortoise.models.classifier'

### ISSUE THREAD

**Issue by vrstybit** [neonbjb/tortoise-tts#272]
**Describe the bug**
After installing Python 3.8.16 on Arch Linux (Kernel: 6.1.6-arch1-g14-1) and following the install guide, everything runs well to the point I'm about to execute do_tts.py - it shows the following error:

`Traceback (most recent call last):
  File "do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "/home/XXX/Downloads/tortoise-tts/tortoise/api.py", line 13, in <module>
    from tortoise.models.diffusion_decoder import DiffusionTts
ModuleNotFoundError: No module named 'tortoise.models.diffusion_decoder'; 'tortoise.models' is not a package
`

**To Reproduce**
`python3.8 do_tts.py --text "XXX" --voice=XXX`

**Expected behavior**
Create TTS with custom text

**Additional context**
Any ideas? Thanks in advance!

**Comment by neonbjb** [comment]
Did you do `python setup.py install`? Sounds like you don't actually have this repo installed, or your clone failed.

**Comment by nerdpferd** [comment]
You should never do any installations tired after work.. oh man, thank you very much this will surely solve the "issue".

**Comment by vrstybit** [comment]
Solved it. Thanks once more!
