### ISSUE TITLE
Process fails when trying to save output

### ISSUE THREAD

**Issue by mstan** [neonbjb/tortoise-tts#285]
Environment: Windows 10 

Attempting the command: `python tortoise/do_tts.py --text "hello world" --voice random --preset fast`

Will run through the entire training process. However, at the very end, when attempting to write to file, I'm seeing the following error:

```
Traceback (most recent call last):
File "E:\TortoiseTTS\tortoise-tts\tortoise\do_tts.py", line 41, in <module>
torchaudio.save(os.path.join(args.output_path, f'{selected_voice}_{k}_{j}.wav'), g.squeeze(0).cpu(), 24000)
File "C:\Users\me\AppData\Roaming\Python\Python\site-packages\torchaudio\backend\soundfile_backend.py", line 435, in save
soundfile.write(file=filepath, data=src, samplerate=sample_rate, subtype=subtype, format=format)
File "C:\Python\lib\site-packages\soundfile-0.11.0-py3.10.egg\soundfile.py", line 340, in write
with SoundFile(file, 'w', samplerate, channels,
File "C:\Python\lib\site-packages\soundfile-0.11.0-py3.10.egg\soundfile.py", line 655, in __init__
self._file = self._open(file, mode_int, closefd)
File "C:\Python\lib\site-packages\soundfile-0.11.0-py3.10.egg\soundfile.py", line 1199, in _open
openfunction = _snd.sf_wchar_open
AttributeError: cffi library 'C:\ProgramData\Miniconda3\Library\bin\sndfile.dll' has no function, constant or global variable named 'sf_wchar_open'
```

**Comment by neonbjb** [comment]
This is an issue with torchaudio, please Google how to get that setup with Windows (or ask chatgpt)

**Comment by mstan** [comment]
I will give that a try. I've attempted a few other online resources with similar error messages to no avail. 

By chance, is there any type of unit test or way to reduce the test loop on attempting to fix this? Right now, I have to attempt to generate a voice line which takes several minutes -- and since it only fails at the absolute end, I'm having to run the entire generation each fix attempt.

**Comment by sbersier** [comment]
I'm pretty sure that if you run the command:
python tortoise/do_tts.py --candidates 1 --text "hello world" --voice random --preset fast
It will run. Does it?
If yes, then, in my opinion, the problem stands on lines 39*43 in do_tts.py

**Comment by sbersier** [comment]
Could you just try:
python tortoise/do_tts.py --candidates 1 --text "hello world" --voice random --preset fast

**Comment by mstan** [comment]
I attempted your command, it didn't work. I decided to just gut my entire environment and setup again and managed to get it going. I'm not sure what the exact fix was, else I'd leave it here. 

Will close for now.
