### ISSUE TITLE
Contrastive search

### ISSUE THREAD

**Issue by Ryu1845** [neonbjb/tortoise-tts#287]
Hi! Contrastive search[0] seems to improve the production of large language models. I was wondering if you thought this could apply to this project. It might fix #237 maybe.

[0] https://github.com/yxuansu/Contrastive_Search_Is_What_You_Need
Also a huggingface blog post https://huggingface.co/blog/introducing-csearch

**Comment by 152334H** [comment]
One problem with applying csearch is the determinism. Not sure if this has changed in newer updates, but when I was using it with transformers 4.24.0, you couldn't apply temperature/nucleus sampling, and outputs would always be the same. 

Currently, the ultra_fast setting for Tortoise takes 16 samples from the GPT model, via stochastic sampling methods. Assuming contrastive search is not enough of an improvement to give consistent quality 1-shot samples (which I expect), you would need to come up with some smart strategy to "randomise" the outputs of contrastive search. Maybe you could vary top-k && palpha. But it will probably produce poor results if you take the full range of [0,1] for palpha.

**Comment by 152334H** [comment]
There is also the question of whether contrastive search will even improve the outputs of this model trained on speech tokens. I might test one-shot samples vs the current sampling strategy and post outputs here later

**Comment by 152334H** [comment]
I tried to use it, but the determinism really breaks things. `num_return_sequences` (aka batch size) needs to be 1, because the sampler is deterministic. This breaks a lot of other inference code (I get some error deep inside `transformers/models/gpt2/modeling_gpt2.py` that I am too reluctant to debug), even after you adjust for the tortoise code itself.

**Comment by Ryu1845** [comment]
Ah alright that's good to know at least. Thanks for trying it out.
