### ISSUE TITLE
internal resampling of the signal

### ISSUE THREAD

**Issue by pepinu** [neonbjb/tortoise-tts#296]
on the [line 153](https://github.com/neonbjb/tortoise-tts/blob/29c1d9e561fbebe01cecc172602c33d44ea46164/tortoise/api.py#L153) there's an internal resampling of the input sequence. 

What's the reasoning behind this? was the diffuser you used pertained for Mel-spectrograms of different frequency?

**Comment by neonbjb** [comment]
Midway through building tortoise I decided to switch from a model that did diffusion directly to waveforms to one that did diffusion to spectrograms. The best available vocoder at the time was Univnet, which worked on 24kHz audio while the rest of my stack worked on 22kHz.

If the whole thing was trained again from scratch, I'd probably just do 24kHz for everything.
