### ISSUE TITLE
AssertionError: This shouldn't happen. My coding sucks.

### ISSUE THREAD

**Issue by xiaoqin00** [neonbjb/tortoise-tts#30]
when i test for a test.txt file,it occurred
 python tortoise/read.py --textfile='./test.txt' --voice random

![image](https://user-images.githubusercontent.com/13318706/167164345-c86d77f6-0e83-423f-bca0-ad9398340b24.png)

**Comment by xiaoqin00** [comment]
when i try it again.
 there is another error.

OSError: jbetker/tacotron_symbols is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`.

**Comment by neonbjb** [comment]
Regarding the second error, should be fixed now.

Regarding the first error: sounds like you are hitting a redaction edge case. I added some code that will dump some information that will help me debug it. Please re-sync to the head of origin/main, re-install (if you did so) and try again. If you run into the error again, re-open this bug and attached the debug files.

Sorry about the required legwork. The redaction code is complicated and difficult to test. I recommend not using it (don't use brackets in your prompts) if you absolutely need stability at the moment.

**Comment by xiaoqin00** [comment]
oh，no
i meet error this morning.


Traceback (most recent call last):
  File "tortoise/do_tts.py", line 27, in <module>
    tts = TextToSpeech(models_dir=args.model_dir)
  File "C:\plan\test3\tortoise-tts-main\tortoise\api.py", line 196, in __init__
    self.autoregressive.load_state_dict(torch.load(f'{models_dir}/autoregressive.pth'))
  File "C:\plan\test3\venv\lib\site-packages\torch\serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\plan\test3\venv\lib\site-packages\torch\serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input

![image](https://user-images.githubusercontent.com/13318706/167235578-2a85f946-8074-4824-b542-e5258b83f880.png)

**Comment by neonbjb** [comment]
One of your model weights was corrupted. Delete the contents of .models/* and try again.

**Comment by xiaoqin00** [comment]
thank u ！

AssertionError: This shouldn't happen. My coding sucks
This error reappeared。
Are there any call restrictions here?
Every time I get this error it's because I'm testing long text。

**Comment by neonbjb** [comment]
Hi, please update. When this occurs again the program will dump some debugging files you can send me.

In general, this program does not perform well with long text inputs. Consider breaking them up.
