### ISSUE TITLE
VQ-VAE network not released

### ISSUE THREAD

**Issue by mlajszczak** [neonbjb/tortoise-tts#33]
Hello! After taking a closer look into the repo it seems that you have not released the VQ-VAE model used to generate discrete speech representations that the autoregressive model was trained on. Is this on purpose? You don't plan to do that in the future?

**Comment by neonbjb** [comment]
Hey there,
Yes, this is on purpose. This is an important ingredient to being able to fine-tune this model, and I do not want to make that process easy/effective for abuse reasons. I am not sure if/when I will release it.

If you are interested in the VQVAE model itself, I would be glad to divulge training details for it so you can build your own. It will not be compatible with the Tortoise codes, though (unless you are really lucky. :) )

**Comment by Nikuson123** [comment]
I would be glad to know the details of the training. I am interested in studying this model.

**Comment by neonbjb** [comment]
> I would be glad to know the details of the training.
To be clear - do you want to know the details of training a speech VQVAE (which I can release right now), or how all of the models that compose TorToiSe are trained? (which I haven't released yet, but will do so in the future)

**Comment by meltingrock** [comment]
> > I would be glad to know the details of the training.
> 
> To be clear - do you want to know the details of training a speech VQVAE (which I can release right now), or how all of the models that compose TorToiSe are trained? (which I haven't released yet, but will do so in the future)

@neonbjb James, well done on building TorToise, reading up about you it seems like you have figured things out for yourself. Quite and achievement and you should tell your parents they have ample reasons to brag about you (most likely they have no idea what it is you actually do, other than "work on computers" ;-) )

I sounds like you were going to release details on training TorToise end to end but with your employment at OpenAI (congrats!!!!!) are you reluctant to do so? If so I can totally understand, but it would be great if you could tell me if this is the case. 

You have given the half the map to the treasure in your research paper, so it is not that you have not been kind enough.

**Comment by neonbjb** [comment]
The [doc I wrote up](https://docs.google.com/document/d/13O_eyY65i6AkNrN_LdPhpUjGhyTNKYHvDrIvHnHe1GA/edit) (and still havent finished.......... :( ) was what I meant when I said I would 'release training details'.

The code for training Tortoise is, and always has been available over in https://github.com/neonbjb/DL-Art-School

What is missing is a really good guide on how to do everything. Unfortunately I just don't have to the time to put that together, nor support the inevitable questions that will crop up if I do. The best recommendation I have is clone DL-Art-School, hook up a debugger and get to it!

**Comment by meltingrock** [comment]
@neonbjb Got it. 

I have started working through DL-Art-School, so wish me luck.

All the best with your endeavours and once again well done.

**Comment by neonbjb** [comment]
Good luck! Nice to see someone taking initiative! I'm sure you'll learn a lot along the way that'll be useful regardless of the outcome.
