### ISSUE TITLE
get_conditioning_latents.py No Output

### ISSUE THREAD

**Issue by R-Olivaw** [neonbjb/tortoise-tts#342]
Issue: When I run get_conditioning_latents.py with this command: 
`python tortoise/get_conditioning_latents.py --voice angie`

The script runs and completes with no errors. However, it also produces no output. I've searched the entire folder structure, and no new .pth files have been created.

I can confirm that do_tts.py works perfectly, so the issue must be with get_conditioning_latents.py. Anyone figure out how to get this working?

**Comment by jdini76** [comment]
what was the solution for this? I am experiencing the same issue.
