### ISSUE TITLE
get_voices() not getting new directories

### ISSUE THREAD

**Issue by R-Olivaw** [neonbjb/tortoise-tts#344]
Hi, I added a new directory called 'tortoise/voices/adriene'. However, when I run the get_voices() util, it's not showing my new directory.

get_voices() returns the following:
`angie
applejack
cond_latent_example
daniel
deniro
emma
freeman
geralt
halle
jlaw
lj
mol
myself
pat
pat2
rainbow
snakes
tim_reynolds
tom
train_atkins
train_daws
train_dotrice
train_dreams
train_empire
train_grace
train_kennard
train_lescault
train_mouse
weaver
william`

I can't figure out why my 'adriene' folder, which is sitting right next to all these other folders, is not returned.

**Comment by raff7** [comment]
I had the same issue, and i figure out what is wrong:

Basically it doesnt find the files in the repository folder itself, but rather in the installed package, so if you first do the setup.py step, and then create a new folder, it will not be able to see it.. just run setup.py again and your folder will now work

**Comment by R-Olivaw** [comment]
Thanks @raff7! That was really driving me crazy! Confirming that running `python setup.py install` fixed this issue for me.
