### ISSUE TITLE
Missing module when installing locally, torchaudio

### ISSUE THREAD

**Issue by kinow** [neonbjb/tortoise-tts#35]
Hi,

I just installed `tortoise-tts`, created a virtual env, `pip install -e .`, then tried the example from `README.md` but got an error.

```bash
(venv) kinow@ranma:~/Development/python/workspace/tortoise-tts$ python tortoise/read.py test.txt
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/tortoise-tts/tortoise/read.py", line 5, in <module>
    import torchaudio
ModuleNotFoundError: No module named 'torchaudio'
```

After `pip install torchaudio`, it worked (downloading data now).

```bash
(venv) kinow@ranma:~/Development/python/workspace/tortoise-tts$ python tortoise/read.py --textfile test.txt
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 2.06k/2.06k [00:00<00:00, 1.25MB/s]
```

Thanks!

**Comment by neonbjb** [comment]
Hi,
torch and torchaudio are not in requirements.txt because they can cause problems when they are installed from pip without the proper incantations. The readme says to install them using the instructions from the pytorch installation page.

**Comment by kinow** [comment]
Ah! Got it, sorry for the noise!
