### ISSUE TITLE
Was the UnivNet vocoder fine-tuned?

### ISSUE THREAD

**Issue by dunky11** [neonbjb/tortoise-tts#38]
Hello first of all great project, this is by far the best zero-shot TTS I've seen yet. I wonder whether the Univnet Vocoder you used was fine-tuned on your dataset or did you simply take the one from https://github.com/mindslab-ai/univnet without further training?
I want to fine-tune the vocoder myself and wonder if I should use the generator weights from this project or from the mindslab repo. 

Also is there any way to get your UnivNet discriminator weights?

**Comment by neonbjb** [comment]
Hey there,
Thanks! I actually used the one available from the mindslab-ai repo. I found it to work fantastic even far out of distribution.

I'd like to train a 44kHz version someday, but I see little benefit in fine-tuning the current version.
