### ISSUE TITLE
ModuleNotFoundError: No module named 'tortoise.models'

### ISSUE THREAD

**Issue by Bananamax** [neonbjb/tortoise-tts#384]
Greetings ladies and gentlemen.

Well I followed the instructions and installed Anaconda and git and pytorch and installed the other stuff via

git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts
python -m pip install -r ./requirements.txt
python setup.py install
conda install -c conda-forge pysoundfile

and then after generating an audio file with "python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast"
it says:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\tortoise-tts\tortoise\do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\ProgramData\anaconda3\tortoise-tts\tortoise\api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise.models'

So what now?

**Comment by Bananamax** [comment]
I am totally fucked here nothing works

**Comment by neonbjb** [comment]
It sounds like `python setup.py install` probably failed. It's looking for the packages from this repo and can't find them. You can also try running your command from the `tortoise` directory.

**Comment by Bananamax** [comment]
Well I did the "python setup.py install" command again and there are no errors as far as I can see. And doing "python do_tts.py --text "I'm going to speak this" --voice random --preset fast" directly in the tortoise directory also doesnt change anything. The same tortoise-models error occurs :(

Lets say I want to reinstall it all try again fresh what are the necessary steps here? Uninstall anaconda and python and also probably delete the set "PATH" and then restart it all or isnt that enough and stuff gets mixed and more errors might occur?

**Comment by bbergeron0** [comment]
If that can assist you, I found it relevant to share my setup in the other issue (https://github.com/neonbjb/tortoise-tts/issues/281#issuecomment-1498111332).

**Comment by Bananamax** [comment]
Yeah thanks for that. So you are not using anything from here: https://pytorch.org/get-started/locally/
What about cuda? I will try your stuff as well

**Comment by bbergeron0** [comment]
Bless you too. Don't forget to close the issue once everything's going smoothly!

**Comment by ganauou** [comment]
how can you make it on gpu? mine keep using cpu. and how to use this ? Create and activate a new python environment named 'venv' using python 3.9 (Other options: 3.8, 3.7)
python3.9 -m venv venv && . venv/bin/activate
i have almost zero knowledge in coding

**Comment by ganauou** [comment]
how did you make it use Gpu instead of Cpu?
