### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by ammartist** [neonbjb/tortoise-tts#39]
After following the installation and all went successfull, when I am trying to test it and I am getting this error:

ModuleNotFoundError: No module named 'tortoise.models'

What am I missing?

**Comment by neonbjb** [comment]
Hey there,
I just ran through the instructions in a fresh conda environment and it worked fine.

Can you please confirm that this step worked successfully:

```
git clone https://github.com/neonbjb/tortoise-tts.git
cd tortoise-tts
python setup.py install
```

What command are you attempting to run?

**Comment by neonbjb** [comment]
I tried a full re-install on windows 11 with a fresh conda env and could not reproduce this. Apologies, it sounds like you're just running into some weird bug. I'm not sure what advice I can offer you. :(

**Comment by JimBilodeau** [comment]
Did anyone figure out the issue?

PS C:\tortoise-tts\tortoise-tts> python tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Traceback (most recent call last):
  File "tortoise/do_tts.py", line 7, in <module>
    from api import TextToSpeech, MODELS_DIR
  File "C:\tortoise-tts\tortoise-tts\tortoise\api.py", line 12, in <module>
    from tortoise.models.classifier import AudioMiniEncoderWithClassifierHead
ModuleNotFoundError: No module named 'tortoise.models'

**Comment by neonbjb** [comment]
You need to install tortoise (or otherwise instruct Python where to find it)

**Comment by TFWol** [comment]
@JimBilodeau I got past that error with `python setup.py install` even after I had already 'installed' it.
