### ISSUE TITLE
scipy missing from requirements.txt

### ISSUE THREAD

**Issue by willstott101** [neonbjb/tortoise-tts#4]
scipy is imported in a few places but is missing from the requirements file :scream:

**Comment by neonbjb** [comment]
Fixed. Thanks for the report!

**Comment by willstott101** [comment]
oh, and `librosa` - I shoulda finished actually getting it to run before reporting. but I'm impatient and my internet is slow - there may be more to come... currently downloading models.

Excited to try it out though - sound great.
