### ISSUE TITLE
OSError: Could not find/load shared object file: llvmlite.dll

### ISSUE THREAD

**Issue by grigorzero** [neonbjb/tortoise-tts#411]
Excuse me, 

I need some help when im trying to run the script.

It is say that i have error  Error was: Could not find module 'llvmlite.dll' (or one of its dependencies). Try using the
 full path with constructor syntax.

But when im check it on the file there is llvmlite.dll. I try to install and uninstall it but it didn't work.

I run on PyCharm

Thank you

**Comment by PragyanSubedi** [comment]
The issue got solved for me by uninstalling numba, llvmlite and reinstalling them on Windows 11 virtual environment.

```
pip uninstall numba llvmlite
pip install numba llvmlite
```
