### ISSUE TITLE
Cannot Run "python setup.py install"

### ISSUE THREAD

**Issue by zalifsif38** [neonbjb/tortoise-tts#412]
OS: Windows 10 x64 Professinal
Python Ver: 3.11

Trying to install setup.py but I am thrown this error: https://pastebin.com/vWjbBdW0

Actions taken:
- Restart computer
- Run Command Prompt, Powerhsell, and Terminal in Admin mode
- Run through Terminal and Powershell instead of Command Prompt

**Comment by zalifsif38** [comment]
Installing python 3.10 fixed it

**Comment by darkzip** [comment]
> Installing python 3.10 fixed it

Did you run the setup.py through 3.10 or was it still through the command prompt after installing 3.10?
