### ISSUE TITLE
How to Fine-Tune the audio in the Google Colab

### ISSUE THREAD

**Issue by Prottoy2938** [neonbjb/tortoise-tts#45]
On this [demo](https://nonint.com/static/tortoise_v2_examples.html), they show a fine-tuned version of the tortoise-tts's recording, which sounds a lot real/better compared to the normally generated one.

![{8FBAEDF3-2CD2-4CE1-9A40-772BF072DB2D} png](https://user-images.githubusercontent.com/51432728/168468525-c9f01798-b333-4e63-8856-e610973d7c48.jpg)

How can I fine-tune the audio or achieve the same result? (on [google colab](https://colab.research.google.com/drive/1wVVqUPqwiDBUVeWWOUNglpGhU3hg_cbR?usp=sharing))?

**Comment by neonbjb** [comment]
Hi there,
I will not be releasing instructions for how to do this, sorry. I will be showing off a few more examples in the week or two, though.
