### ISSUE TITLE
Combining voices not working for do_tts.py

### ISSUE THREAD

**Issue by wavymulder** [neonbjb/tortoise-tts#46]
'&' character not working to combine voices for do_tts.py

Works as expected for read.py

**Comment by wavymulder** [comment]
Also, would it be possible to use the candidates argument for read.py?

**Comment by neonbjb** [comment]
Do you have any idea on how this would be implemented? How would the program select which candidate to use for the final audio clip it spits out?

I guess it could output several candidates for each phrase, then leave it up to the user to select the best one and concatenate all the clips. Is that what you were thinking?

**Comment by neonbjb** [comment]
Sure, I can probably think up some clever way to do this. I'll package these fixes together.

**Comment by neonbjb** [comment]
Both of these suggestions have been implemented, cheers!
