### ISSUE TITLE
Keeping model after usage and importing own pre trained models.

### ISSUE THREAD

**Issue by romeronathan** [neonbjb/tortoise-tts#47]
I was wondering if this was possible and if you could clarify/instruct how to use one's own pretrained models. 
I noticed this as an update point in V2.1. 
Basically, I want to keep the trained model of a custom voice I make and was wondering if that was possible.

**Comment by neonbjb** [comment]
Hi - yes, I added this capability to show off fine-tuned models to friends & family, but I do not plan to release documentation on how to build your own fine-tuned models. Fine-tuned models are too good at impersonation and I did not intend for tortoise to be a "deep fake" generator. 

I have had a lot of requests about this, I am considering building fine-tuned models as a paid service for legitimate uses. Please stay tuned, or if you are immediately interested, you can reach out to me directly at jbetker at gmail.
