### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by planetrocke** [neonbjb/tortoise-tts#48]
I am looking for parallel support for multi-GPUs. I see pieces of this in autoregressive model, I am just wondering if there is a particular way to accomplish this with UnifiedVoice. Thanks.

**Comment by neonbjb** [comment]
Oh I see what you are looking for. I don't have access to devices that support this, but my understanding is that you should be able to pool the devices at the hardware level (such that programs like mine just see a single GPU).

Unfortunately supporting ultra-long context lengths isn't as easy as just throwing more memory at the problem. The models were only trained to process up to 20 seconds of audio at a time. For one thing, they have fixed positional embeddings which enforces that limit. 

Supporting longer context lengths is possible, but it would require a lot of work, including re-building my dataset to cater towards longer audio and re-training the two big models to a small extent.

**Comment by scott-vector** [comment]
Ok. That is a fantastic explanation. I guess I already knew read.py does partials so that makes sense as well.
