### ISSUE TITLE
Cantonese + English model

### ISSUE THREAD

**Issue by Keith-Hon** [neonbjb/tortoise-tts#493]
I have finetuned a model for Cantonese, a tonal language, like Mandarin. I also tried to mix it with english.

Cantonese
https://soundcloud.com/keith-hon/0a-2

Cantonese + English
https://soundcloud.com/keith-hon/cantonese-english-mixed-tts-with-voice-clone

which sounds decent in my opinon. However, I will need to train a custom CLVP model to pick the best outputs from the diffusion model.

I plan to mix with other asian languages as well.

**Comment by edwardmfho** [comment]
Thanks Keith, really interesting and the outcome is pretty good too!

**Comment by lilinrestart** [comment]
> 



> 我为粤语微调了一个模型，粤语是一种声调语言，就像普通话一样。我还尝试将其与英语混合。
> 
> 粤语 https://soundcloud.com/keith-hon/0a-2
> 
> 粤语 + 英语 https://soundcloud.com/keith-hon/cantonese-english-mixed-tts-with-voice-clone
> 
> 我认为这听起来不错。但是，我需要训练自定义 CLVP 模型以从扩散模型中选择最佳输出。
> 
> 我也计划与其他亚洲语言混合。

用中文普通话+英文微调模型有实现的存储库吗，跪求：）

**Comment by Kevin-free** [comment]
> I have finetuned a model for Cantonese, a tonal language, like Mandarin. I also tried to mix it with english.
> 
> Cantonese https://soundcloud.com/keith-hon/0a-2
> 
> Cantonese + English https://soundcloud.com/keith-hon/cantonese-english-mixed-tts-with-voice-clone
> 
> which sounds decent in my opinon. However, I will need to train a custom CLVP model to pick the best outputs from the diffusion model.
> 
> I plan to mix with other asian languages as well.

This Cantonese effect is great! Is this project implemented? @Keith-Hon

**Comment by janelawrence** [comment]
@Keith-Hon , Hi Keith, I wonder if this finetuned model available yet?
