### ISSUE TITLE
does it work with any language?

### ISSUE THREAD

**Issue by loboere** [neonbjb/tortoise-tts#5]

**Comment by Nikuson123** [comment]
it seems to be written that only English.

**Comment by neonbjb** [comment]
Only English for now, sorry. If you are interested in bringing this to your native language and have access to compute and the time required to gather the dataset, reach out to me.

**Comment by jjandnn** [comment]
> 暂时只有英文，抱歉。如果您有兴趣将其转换为您的母语，并且可以访问计算和收集数据集所需的时间，请与我联系。

感谢您的作品，我很喜欢。
我有这样几个疑问：可不可以直接使用类似AISHELL-3这样的数据集？你指的可以访问计算指的是什么？是指我们可以参与训练模型吗？
最后，我想说的一点是，您防止滥用的初衷我很认同。但它不会改变此类技术的全面拓展与应用的出现，因为这就是未来。技术本身没有善恶。只有用的人有合法与不合法。这一点，您可以看nemo、speechbrain等综合类的项目。另外，如您所说，现阶段，乌龟的推理速度还不能支持欺骗，恰恰它可以被高效的用于创作艺术作品。
Thank you for your work, I like it very much.

I have a few questions: Can I use a data set like AISHELL-3 directly?What do you mean to access the calculation refers to?Can we participate in the training model?

In the end, I want to say that I agree with the original intention of preventing abuse.But it does not change the comprehensive expansion and application of such technologies, because this is the future.The technology itself has no good and evil.Only those who use it are legal and illegal.In this regard, you can watch comprehensive projects such as Nemo, Speechbrain.In addition, as you say, at this stage, the speed of turtles cannot support deception, which can be efficiently used for creating art works.

**Comment by neonbjb** [comment]
Hey,
Here is what you need to train this:
- a wav2vec or similar asr model for your language
- at least 10,000 hours of usable spoken language, with no environmental noises, music, etc. This does not need to be transcribed. I used audiobooks and podcasts for english.
- approximately 16 months total of v100 time

I do not think aishell is enough data to train this.

If you have access to these resources and can commit to open sourcing your results, contact me.

**Comment by jjandnn** [comment]
> 嘿， 这是你需要训练的：
> 
> * 适用于您的语言的 wav2vec 或类似的 asr 模型
> * 至少 10,000 小时的可用口语，没有环境噪音、音乐等。这不需要转录。我用英语有声读物和播客。
> * 大约 16 个月，总共 v100 时间
> 
> 我认为 aishell 的数据不足以训练这一点。
> 
> 如果您可以访问这些资源并且可以承诺开源您的结果，请与我联系。

Thank you very much for your answer。
I'd love to open source, so I'll see if I can organize an effective and eligible data set。

**Comment by neonbjb** [comment]
Please reach out to me directly, jbetker@gmail.com.

**Comment by QiFuChina** [comment]
> Hey, Here is what you need to train this:
> 
> * a wav2vec or similar asr model for your language
> * at least 10,000 hours of usable spoken language, with no environmental noises, music, etc. This does not need to be transcribed. I used audiobooks and podcasts for english.
> * approximately 16 months total of v100 time
> 
> I do not think aishell is enough data to train this.
> 
> If you have access to these resources and can commit to open sourcing your results, contact me.

What about use AISHELL-3、aidatatang_200zh and Aishell togeter? Does it solve data amount problem?

**Comment by neonbjb** [comment]
Depends on your objective I guess. I think it might produce a pretty realistic voice renderer, but only for very few voices, because of:

 > 218 Mandarin voices

I think this is the principle problem I see with AI-SHELL and a lot of datasets. My dataset had many thousands of voices and I believe that is a critical element to getting something (closer to) capable of universal voices.

**Comment by Stardust-minus** [comment]
> Hey, Here is what you need to train this:
> 
> * a wav2vec or similar asr model for your language
> * at least 10,000 hours of usable spoken language, with no environmental noises, music, etc. This does not need to be transcribed. I used audiobooks and podcasts for english.
> * approximately 16 months total of v100 time
> 
> I do not think aishell is enough data to train this.
> 
> If you have access to these resources and can commit to open sourcing your results, contact me.

I have enough GPUand I want to train a chinese model.
But for me,I only have about 1,000 hours voice for muti speaker.
Iwant to know if he voice its generate is binded with the data I used.
My target is to train a tts model for an Game character.Should I use open dataset such as aizhdata_200 and mix it with my Data?
Im glad to recive your reply,and if you want to help me to train the model,I will share it!

**Comment by neonbjb** [comment]
Yes I'd recommend blending as much data as you can find. The more voices you can include in your dataset, the better the multi voice performance will be.

The first step will be transcribing your dataset. Take a look at my ocotillo GitHub repo for some ideas on how this can be done. I believe there are wav2vec models for Chinese available that you can slot in fairly easily.

**Comment by andupotorac** [comment]
@neonbjb James, thanks for the info on what might be needed for the dataset. Please provide a walk-through on how this might be achieved so that everyone in the community can try to pull together resources for different languages and add them to the primary model.

**Comment by neonbjb** [comment]
1. Go on the internet
2. Find lots of speech
3. Download it
4. Clean it
5. Chunk it into <60s bits
6. Transcribe it
7. Train an AR model on it!

**Comment by neonbjb** [comment]
That's not really how it works, unfortunately. The link you provided is an italian ASR model which will take in speech and produce italian text. You'd now need to go gather a huge dataset of Italian speech, use this model to transcribe it all, then train the Tortoise stack from scratch.

**Comment by neonbjb** [comment]
Hey, sorry I can't really help you with this.

**Comment by Xonem1** [comment]
> hey yall - if you have audio that you want this trained on, i have 8x a6000s i'd be happy to train it on. just reach out to me in discord @devinschumacher#1337 | cheers
> 
> @neonbjb @solidsnake777999 @andupotorac @Stardust-minus

How many audios in spanish and its ok if i provide it thru gdrive?

**Comment by pablopda** [comment]
For transcribing to Spanish, you can use Whisper that has a very low error in speach-to-text in Spanish. 

For audio, we can use audiobooks ? Where can we read about the English corpus to get an idea about the kind of content we should grab?.
> 1. Go on the internet
> 2. Find lots of speech
> 3. Download it
> 4. Clean it
> 5. Chunk it into <60s bits
> 6. Transcribe it
> 7. Train an AR model on it!

**Comment by neonbjb** [comment]
I mean you should generally use common sense. Listen to your dataset and read the transcriptions. Is the content good enough for a human to learn from? If so, it's good enough for ML too!

I wrote about my dataset collection and curation in the paper linked in the repo README.

**Comment by devinschumacher** [comment]
> > hey yall - if you have audio that you want this trained on, i have 8x a6000s i'd be happy to train it on. just reach out to me in discord @devinschumacher#1337 | cheers
> > @neonbjb @solidsnake777999 @andupotorac @Stardust-minus
> 
> How many audios in spanish and its ok if i provide it thru gdrive?

hello! how big are the files? you can send them over in G drive, but please ping me in discord bc i want to tag francis to make sure i give you the correct instructions - hes the expert. Im just the hype man :)

**Comment by yoanpierov** [comment]
Hello! 
First, thank you for this amazing project. 
My question is, how to make a simple small model on Bulgarian language, I don't have the compute power of V100 and 16 months, but indeed i do have 10 hours of Bulgarian speech.

**Comment by devinschumacher** [comment]
hi @yoanpierov - we have 8x a6000s im happy to use to train a model in bulgarian if you can provide the necessary source data.

message me in our discord so i can sync this convo with francis and we can make a plan to get it done for you.

its @ https://serp.ly/@serp/discord

**Comment by Crtque** [comment]
Hello! @neonbjb 
I found this model https://huggingface.co/SerCe/tortoise-tts-ruslan, how can i use it instead or with english model?

**Comment by neonbjb** [comment]
I have not trained any other models you'll need to contact whomever trained that model.

**Comment by guilhermeotto2** [comment]
is there any other voice cloner that clones in multiple languages?

**Comment by baptx** [comment]
@neonbjb It would be useful to keep this issue open since it is not fixed, so it is more visible for people who want to contribute.
@guiottoo There is https://github.com/serp-ai/bark-with-voice-clone that works in theory with foreign languages but I did not get good clone results with French (sometimes the sound is better when using OGG instead of WAV as input).
