### ISSUE TITLE
Error - multiple values for keyword argument 'logits_processor'

### ISSUE THREAD

**Issue by mr-segfault** [neonbjb/tortoise-tts#50]
Hello,

Trying to run the current branch's example use case from the guide and receive the following error:

`python3 tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Generating autoregressive samples..
  0%|                                                                                                                       | 0/96 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/ghost/tortoise-tts/tortoise/do_tts.py", line 30, in <module>
    gen = tts.tts_with_preset(args.text, k=args.candidates, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
  File "/home/ghost/tortoise-tts/tortoise/api.py", line 305, in tts_with_preset
    return self.tts(text, **kwargs)
  File "/home/ghost/tortoise-tts/tortoise/api.py", line 387, in tts
    codes = self.autoregressive.inference_speech(auto_conditioning, text_tokens,
  File "/usr/local/lib/python3.9/dist-packages/TorToiSe-2.3.0-py3.9.egg/tortoise/models/autoregressive.py", line 498, in inference_speech
  File "/home/ghost/.local/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/home/ghost/.local/lib/python3.9/site-packages/transformers/generation_utils.py", line 1016, in generate
    return self.sample(
TypeError: transformers.generation_utils.GenerationMixin.sample() got multiple values for keyword argument 'logits_processor'`

Any advice? Thanks

**Comment by mr-segfault** [comment]
Hey, thank you for the quick reply.

That did the trick.

Here's my full terminal output so you can see any specific versions that were pulled, etc.

`pip install -U transformers
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: transformers in /home/ghost/.local/lib/python3.9/site-packages (4.10.3)
Collecting transformers
  Downloading transformers-4.19.2-py3-none-any.whl (4.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.2/4.2 MB 8.4 MB/s eta 0:00:00
Requirement already satisfied: packaging>=20.0 in /home/ghost/.local/lib/python3.9/site-packages (from transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /usr/lib/python3/dist-packages (from transformers) (5.3.1)
Requirement already satisfied: filelock in /home/ghost/.local/lib/python3.9/site-packages (from transformers) (3.4.2)
Requirement already satisfied: regex!=2019.12.17 in /home/ghost/.local/lib/python3.9/site-packages (from transformers) (2022.1.18)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from transformers) (2.25.1)
Collecting tokenizers!=0.11.3,<0.13,>=0.11.1
  Downloading tokenizers-0.12.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (6.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 23.8 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /home/ghost/.local/lib/python3.9/site-packages (from transformers) (4.45.0)
Requirement already satisfied: numpy>=1.17 in /home/ghost/.local/lib/python3.9/site-packages (from transformers) (1.19.5)
Requirement already satisfied: huggingface-hub<1.0,>=0.1.0 in /home/ghost/.local/lib/python3.9/site-packages (from transformers) (0.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /home/ghost/.local/lib/python3.9/site-packages (from huggingface-hub<1.0,>=0.1.0->transformers) (4.0.1)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /usr/lib/python3/dist-packages (from packaging>=20.0->transformers) (2.4.7)
Installing collected packages: tokenizers, transformers
  Attempting uninstall: tokenizers
    Found existing installation: tokenizers 0.10.3
    Uninstalling tokenizers-0.10.3:
      Successfully uninstalled tokenizers-0.10.3
  Attempting uninstall: transformers
    Found existing installation: transformers 4.10.3
    Uninstalling transformers-4.10.3:
      Successfully uninstalled transformers-4.10.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
rudalle 1.0.0 requires transformers~=4.10.2, but you have transformers 4.19.2 which is incompatible.
Successfully installed tokenizers-0.12.1 transformers-4.19.2
WARNING: You are using pip version 22.0.4; however, version 22.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
ghost@section9:~/tortoise-tts$ python3 tortoise/do_tts.py --text "I'm going to speak this" --voice random --preset fast
Generating autoregressive samples..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 96/96 [01:07<00:00,  1.42it/s]
Computing best candidates using CLVP and CVVP
  0%|                                                                                                                       | 0/96 [00:00<?, ?it/s]/home/ghost/.local/lib/python3.9/site-packages/torch/utils/checkpoint.py:25: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn("None of the inputs have requires_grad=True. Gradients will be None")
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 96/96 [00:07<00:00, 12.75it/s]
Transforming autoregressive outputs into audio..
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:05<00:00, 14.65it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:04<00:00, 18.12it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:03<00:00, 20.34it/s]`

**Comment by neonbjb** [comment]
Thanks, I'll upload the requirements adjustment tonight!
