### ISSUE TITLE
Classifiers for text and speech data processing 

### ISSUE THREAD

**Issue by deadlockvn** [neonbjb/tortoise-tts#507]
Hi there,
I  read in your paper that you used trained classifiers to process an extended 49 000 hours of text and speech which could remove noises, music, reverbs, bad voice qualities like phone calls, etc...
Could you please release the code for this? I can use it to collect data for other languages. You need at least 20k hours of clean speech data to train 4 different models, for any new languages? What model needs to be retrained? Or do you have to retrain them all? 
I appreciate it very much what you have done here. It is a great contribution to the community. Thank you!
I'd like to train it for some Asian languages.

**Comment by neonbjb** [comment]
Hey there, check out this issue: https://github.com/neonbjb/tortoise-tts/issues/334
