### ISSUE TITLE
CoLab Error wih Tortoise.api import TextToSpeech

### ISSUE THREAD

**Issue by ConflictLabs** [neonbjb/tortoise-tts#519]
Using Colab adjusted the dependencies in 'requirements.txt' to reflect current needs of:
nbconvert==6.4.4
tornado==6.3.1

but import TextToSpeech error is:
ValueError: `Field` default cannot be set in `Annotated` for 'num_Annotated[str, FieldInfo(min_length=1, extra={})]'

Any suggestions on how to fix this?

**Comment by manmay-nakhashi** [comment]
@ConflictLabs pull latest changes.

**Comment by manmay-nakhashi** [comment]
downgrade nbconvert to the version which is mentioned in requirements.txt

**Comment by V-Cooper** [comment]
Update the pydantic library.

`pip install pydantic==1.9.1`

https://github.com/neonbjb/tortoise-tts/issues/515

**Comment by ConflictLabs** [comment]
Thanks all, problem still exists.

I'm doing a fresh pull no modification and it returns this error:
ValueError: `Field` default cannot be set in `Annotated` for 'num_Annotated[str, FieldInfo(min_length=1, extra={})]'

I fix this error:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bokeh 2.4.3 requires tornado>=5.1, but you have tornado 4.2 which is incompatible.
distributed 2022.12.1 requires tornado>=6.0.3, but you have tornado 4.2 which is incompatible.
google-colab 1.0.0 requires tornado==6.3.1, but you have tornado 4.2 which is incompatible.
jupyter-server 1.24.0 requires nbconvert>=6.4.4, but you have nbconvert 5.3.1 which is incompatible.
jupyter-server 1.24.0 requires tornado>=6.1.0, but you have tornado 4.2 which is incompatible.
notebook 6.4.8 requires tornado>=6.1, but you have tornado 4.2 which is incompatible.
terminado 0.17.1 requires tornado>=6.1.0, but you have tornado 4.2 which is incompatible.

By updating 'requirements.txt' to 'tornado==6.1.0'

However, it still leaves the original error, of:
/usr/local/lib/python3.10/dist-packages/pydantic/fields.cpython-310-x86_64-linux-gnu.so in pydantic.fields.ModelField._get_field_info()
ValueError: `Field` default cannot be set in `Annotated` for 'num_Annotated[str, FieldInfo(min_length=1, extra={})]'

Even after updating to 'pydantic==1.9.1' still getting the same error.

**Comment by olaviinha** [comment]
Solution mentioned above (`pydantic==1.9.1`) solves the problem.

Note that after installing `pydantic==1.9.1`, you need to restart runtime and make sure not to downgrade it back to `pydantic==1.9.0` as stated in _requirements.txt_. I would suggest simply editing _requirements.txt_ before installing the requirements; that way it's still going to say 1.9.1 after runtime restart, so safest way to go in Colab imo.

**Comment by ConflictLabs** [comment]
Thank you, yes that worked well, appreciate the pointers
