### ISSUE TITLE
Very slow generation time

### ISSUE THREAD

**Issue by BarnabyssJones** [neonbjb/tortoise-tts#535]
When I try to use the read.py script to read several sentences, it takes an incredibly long time to generate an audio sample. I only have a few sentences, and it takes hours despite having a 3080ti, and this doesn't occur with the di_tts. py script for a single phrase. Is there a reason for this?

**Comment by AritraroyDxl97** [comment]
its maybe the compiler problem!

**Comment by BarnabyssJones** [comment]
Hmm... any recommendations? I'm quite the beginner here.

**Comment by BarnabyssJones** [comment]
> its maybe the compiler problem!

It sounds like you've seen this problem before. Can I ask what the compiler problem actually is specifically? As it is, it's almost unusuable for anything more than a single sentence.

**Comment by manmay-nakhashi** [comment]
pull the latest changes and check
