### ISSUE TITLE
AttributeError: 'DeepSpeedGPTInference' object has no attribute 'dtype'. Did you mean: 'type'?

### ISSUE THREAD

**Issue by rsxdalv** [neonbjb/tortoise-tts#546]
Running in a Google Colab, original issue:
https://github.com/rsxdalv/tts-generation-webui/issues/107

Inference works without deepspeed enabled.

**Comment by TomOerlemans** [comment]
I had the same issue with the latest version of DeepSpeed (v0.10.0), however the version specified in requirements.txt does work:

```
pip uninstall deepspeed
pip install deepspeed==0.8.3
```

**Comment by rsxdalv** [comment]
> I have the same problem with the latest version of DeepSpeed (v0.10.0). Fortunately, the version specified in requirements.txt does work for me:
> 
> ```
> pip uninstall deepspeed
> pip install deepspeed==0.8.3
> ```

Thank you, it appears to work!

Probably the repository should be pinned to 0.8.3; however I worry about the incompatibility with other projects.
