### ISSUE TITLE
How to improve voice quality for other languages?

### ISSUE THREAD

**Issue by drewdru** [neonbjb/tortoise-tts#552]
Hello. I'm trying to use [tortoise-tts-ruslan model](https://huggingface.co/SerCe/tortoise-tts-ruslan/tree/main/model), but it sounds odd.
I added ruslan.pth to the .model directory and tried to run it with this command:
```
python tortoise/do_tts.py --text "Мне всегда готовы предоставить работу, которая обеспечит нормальное биологическое существование." --voice ruslan --preset fast --model_dir .model
```

I also tried using it with the high_quality preset and with 1000 examples in tortoise/voices/ruslan, but it doesn't help at all. It still sounds close to English pronunciation. What parameters should I use for do_tts to fix this? Should I change anything else?

**Comment by manmay-nakhashi** [comment]
@drewdru you'll need 10k hours of data to train this model  [tortoise-tts-ruslan model](https://huggingface.co/SerCe/tortoise-tts-ruslan/tree/main/model) this model is trained by someone else.

**Comment by manmay-nakhashi** [comment]
Please check if there is update in tokenizer 🤔

**Comment by drewdru** [comment]
https://huggingface.co/SerCe/tortoise-tts-ruslan/discussions/1
https://huggingface.co/SerCe/tortoise-tts-ruslan/discussions/2
