### ISSUE TITLE
DeepSpeed on Apple Silicon?

### ISSUE THREAD

**Issue by fakerybakery** [neonbjb/tortoise-tts#566]
Hi,
I saw that PR #550 recently added support for MPS/M1, but the Readme says DeepSpeed is not supported on Apple Silicon:
> Be aware that DeepSpeed is disabled on Apple Silicon since it does not work. The flag `--use_deepspeed` is ignored. You may need to prepend `PYTORCH_ENABLE_MPS_FALLBACK=1` to the commands below to make them work since MPS does not support all the operations in Pytorch.
However, [DeepSpeed PR #3907](https://github.com/microsoft/DeepSpeed/pull/3907) adds support for Apple Silicon.
Is there any way to run DeepSpeed on M1 with Tortoise TTS?
Thank you!

**Comment by manmay-nakhashi** [comment]
@fakerybakery deepspeed doesn't support Apple silicon.

**Comment by manmay-nakhashi** [comment]
@fakerybakery example in deepspeed is for training not for inference, i think you can try if it works for you , feel free to cntribute over here

**Comment by SSardorf** [comment]
@fakerybakery @manmay-nakhashi 
As far as I can tell, it works. I've enabled deep speed in my PR which enables mps support.
However, I it doesn't seem to have much of an effect on the speed of inference
#837
