### ISSUE TITLE
Excessive use of Vram on colab

### ISSUE THREAD

**Issue by Glow-storm** [neonbjb/tortoise-tts#576]
I wanted to ask, even on 16gb vram , it is still running out of memory 
![image](https://github.com/neonbjb/tortoise-tts/assets/132766898/b8e87747-e138-4908-8839-5b495aa7a38e)
![image](https://github.com/neonbjb/tortoise-tts/assets/132766898/3f873128-8840-4095-85c9-ae4a8eb8afa6)
![image](https://github.com/neonbjb/tortoise-tts/assets/132766898/293f6a73-1c18-4f57-8d4d-cdb1fc95175f)

can anyone tell me how to run it in colab using deepspeed

**Comment by Glow-storm** [comment]
It seems to give an error an CLip

**Comment by Glow-storm** [comment]
Also I have 2 gpu's is there a way to utlize my second GPU

**Comment by manmay-nakhashi** [comment]
Please share your code in the issue , can't solve just by looking at the error , normally it should run on 16gb GPU

**Comment by Glow-storm** [comment]
this is the code , it works when I dont use deepspeed but when i use deepspeed I run out of memory 


`# -*- coding: utf-8 -*-
"""copy of tortoise-tts.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NxiY3zHN4Nd8J3YAqFsbYaOB71IiLE04

Welcome to Tortoise! 🐢🐢🐢🐢

Before you begin, I **strongly** recommend you turn on a GPU runtime.

There's a reason this is called "Tortoise" - this model takes up to a minute to perform inference for a single sentence on a GPU. Expect waits on the order of hours on a CPU.
"""

!pip3 install deepspeed

# Commented out IPython magic to ensure Python compatibility.
# the scipy version packaged with colab is not tolerant of misformated WAV files.
# install the latest version.
!pip3 install -U scipy

!git clone https://github.com/neonbjb/tortoise-tts.git
# %cd tortoise-tts
!pip3 install -r requirements.txt
!pip3 install deepspeed
!pip3 install transformers==4.19.0 einops==0.5.0 rotary_embedding_torch==0.1.5 unidecode==1.3.5
!python3 setup.py install

# Imports used through the rest of the notebook.
import torch
import torchaudio
import torch.nn as nn
import torch.nn.functional as F

import IPython

from tortoise.api import TextToSpeech
from tortoise.utils.audio import load_audio, load_voice, load_voices

# This will download all the models used by Tortoise from the HuggingFace hub.
tts = TextToSpeech(use_deepspeed=True,kv_cache=True)

# This is the text that will be spoken.
text = "Thanks for reading this article. I hope you learned something."

# Pick a "preset mode" to determine quality. Options: {"ultra_fast", "fast" (default), "standard", "high_quality"}. See docs in api.py
preset = "ultra_fast"

# Optionally, upload use your own voice by running the next two cells. I recommend
# you upload at least 2 audio clips. They must be a WAV file, 6-10 seconds long.
CUSTOM_VOICE_NAME = "martin"

import os
from google.colab import files

custom_voice_folder = f"tortoise/voices/{CUSTOM_VOICE_NAME}"
os.makedirs(custom_voice_folder)
for i, file_data in enumerate(files.upload().values()):
  with open(os.path.join(custom_voice_folder, f'{i}.wav'), 'wb') as f:
    f.write(file_data)

# Generate speech with the custotm voice.
CUSTOM_VOICE_NAME = "martin"
voice='freeman'
voice_samples, conditioning_latents = load_voice(voice)
gen = tts.tts_with_preset(text, voice_samples=voice_samples, conditioning_latents=conditioning_latents,
                          preset=preset)
torchaudio.save(f'generated-{CUSTOM_VOICE_NAME}.wav', gen.squeeze(0).cpu(), 24000)
IPython.display.Audio(f'generated-{CUSTOM_VOICE_NAME}.wav')

`

**Comment by Glow-storm** [comment]
It seems setting autoregressive batch to 12 or less is able to stop the out of memory error 
tts = TextToSpeech(kv_cache=True,autoregressive_batch_size=12,use_deepspeed=True)
But I still wanted to know why this error was coming , 

As for If someone wants a working Colab for this repo use my above given code it works but this line given in this comment

**Comment by manmay-nakhashi** [comment]
you can remove autoregressive_batch_size from your api and run it again and pass half=True.

**Comment by Glow-storm** [comment]
ok thanks
