### ISSUE TITLE
Mistake from autoregressive.py - GPT2InferenceModel

### ISSUE THREAD

**Issue by Keith-Hon** [neonbjb/tortoise-tts#584]
[            text_emb = text_emb + self.text_pos_embedding(text_emb)](https://github.com/neonbjb/tortoise-tts/blob/f04f95e30245c85996be3af068cba4890952b1a1/tortoise/models/autoregressive.py#L131C13-L131C68)

shouldn't it be
text_emb = text_emb + self.text_pos_embedding(text_inputs)

instead?

**Comment by neonbjb** [comment]
Naw, I wrote a class that uses the input (`text_emb`) to determine the sequence length: 

https://github.com/neonbjb/tortoise-tts/blob/f04f95e30245c85996be3af068cba4890952b1a1/tortoise/models/autoregressive.py#L223

It doesn't actually matter what you pass in as long as dim 1 is the sequence length and it's on the right device.
