### ISSUE TITLE
Maybe not a real issue. Strange audio produced.

### ISSUE THREAD

**Issue by rgkirch** [neonbjb/tortoise-tts#590]
I don't know if this is a fair issue to file. I've made about 10 clips and this came out of one. It has a very strange sound in the middle of a sentence.

https://github.com/neonbjb/tortoise-tts/assets/6143833/40f73b2d-76c0-479c-a3e1-9b529b129d2c

![image](https://github.com/neonbjb/tortoise-tts/assets/6143833/8f2361e4-d4f5-4f51-961f-c87e286be01b)

**Comment by rgkirch** [comment]
--preset fast --voice geralt

**Comment by jnberger** [comment]
It doesn't do well with long passages, try splitting up the sentences

**Comment by rgkirch** [comment]
I'll be back if it croaks again on a single sentence. I was feeding it long passages.
