### ISSUE TITLE
Colab causes "device-side assert" errors

### ISSUE THREAD

**Issue by mrseeker** [neonbjb/tortoise-tts#6]
The following error is generated when I am trying to use my own text:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-10-ac2542568414>](https://localhost:8080/#) in <module>()
      7     conds.append(c)
      8 
----> 9 gen = tts.tts_with_preset(text, conds, preset)
     10 torchaudio.save('generated.wav', gen.squeeze(0).cpu(), 24000)
     11 IPython.display.Audio('generated.wav')

1 frames
[/content/tortoise-tts/api.py](https://localhost:8080/#) in tts(self, text, voice_samples, k, verbose, num_autoregressive_samples, temperature, length_penalty, repetition_penalty, top_p, max_mel_tokens, typical_sampling, typical_mass, clvp_cvvp_slider, diffusion_iterations, cond_free, cond_free_k, diffusion_temperature, **hf_generate_kwargs)
    278                  Sample rate is 24kHz.
    279         """
--> 280         text = torch.IntTensor(self.tokenizer.encode(text)).unsqueeze(0).cuda()
    281         text = F.pad(text, (0, 1))  # This may not be necessary.
    282 

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.

**Comment by neonbjb** [comment]
This is because your text is too long.  Break it up into multiple parts or use read.py.

I'll add a better error message.

**Comment by neonbjb** [comment]
Done. You should get a better error message now.
