### ISSUE TITLE
how do reference CLIPs work?

### ISSUE THREAD

**Issue by nikuson** [neonbjb/tortoise-tts#61]
can you please see the materials on how the reference clip work?  Thanks in advance.

**Comment by neonbjb** [comment]
what do you mean?

**Comment by nikuson** [comment]
I am interested to know a little more about the process of obtaining “conditioning latent". Maybe you can throw off links to materials that you were inspired by?

**Comment by neonbjb** [comment]
This was entirely my own design. I would say the closest inspiration came from multispeech: https://arxiv.org/pdf/2006.04664.pdf where they use a speaker ID that is fed into a learned embedding that the model uses to decode the voice. 

When I read that, I figured that if a model can learn to associate speaker qualities with a single ID, why wouldn't it be able to learn those same qualities from an actual clip of spoken text?

Of course this only works if you have a large dataset with many thousands of different speakers. I don't think this would work using just LibriTTS, for example. For that use-case, I believe what the authors of multispeech did was the best approach.
