### ISSUE TITLE
Method for Faster Inference

### ISSUE THREAD

**Issue by fakerybakery** [neonbjb/tortoise-tts#614]
Hi, might it be possible to merge [this repository](https://github.com/metavoicexyz/tortoise-tts) upstream? It's slightly faster than the original version. Thanks!

**Comment by jhowilbur** [comment]
@fakerybakery, can you help me understand the main point of making this other repo faster?
I tried to find it here in the commits, but I need help finding out why.

**Comment by fakerybakery** [comment]
Hi @jhowilbur 
In the API repo, the authors mentioned that in their fork they made it 30% faster:

> We have made some improvements to Tortoise to make the inference ~30% faster, and welcome contributions on our repo to improve it further!
- [https://github.com/metavoicexyz/tortoise-tts-modal-api](Source)

The commit messages say they made it faster by not moving the models between CPU and GPU.

Hope this helps!

**Comment by fakerybakery** [comment]
Hi @manmay-nakhashi, has this been resolved?

**Comment by manmay-nakhashi** [comment]
Yes we don't do offloading to cpu

**Comment by fakerybakery** [comment]
Just to clarify, the improvements in this fork have already been merged?

**Comment by fakerybakery** [comment]
The api_fast.py can't work on MPS (#658) since the fast API requires autocast and autocast isn't yet supported [on MPS](https://github.com/pytorch/pytorch/pull/99272).

> Yes we don't do offloading to cpu in api_fast.py

Does this mean support for the regular API is not planned @manmay-nakhashi?
