### ISSUE TITLE
XTTS-like Implementation?

### ISSUE THREAD

**Issue by fakerybakery** [neonbjb/tortoise-tts#621]
Hi, might it be possible to use some of the principles of [XTTS](https://huggingface.co/coqui/XTTS-v1) to speed this up? The main issue with XTTS is that the license is very restrictive, and I was wondering if it might be possible to use some of their ideas to make it faster? Thanks in advance!

**Comment by manmay-nakhashi** [comment]
pushing it in 1 or 2 days.
