### ISSUE TITLE
I can confirm this will run with NO GPU

### ISSUE THREAD

**Issue by wgaylord** [neonbjb/tortoise-tts#624]
I have done some testing and I can confirm using the CPU version of the pytorch libraries ( torch, torchaudio and torchvision) this will run without any GPU installed in a system. Yes it does take a while (about 7 min total when set to fast) but it does fully work.

**Comment by jhowilbur** [comment]
Same here on my machine like @wgaylord mentioned

**Comment by Dynamical-Code** [comment]
how long of a clip does it generate in 7 minutes

**Comment by baptx** [comment]
It would be useful to mention in the README.md that it also works with the CPU only because it is currently misleading:

> If you want to use this on your own computer, you must have an NVIDIA GPU.
