### ISSUE TITLE
multi gpu support

### ISSUE THREAD

**Issue by 1gN0bl3** [neonbjb/tortoise-tts#647]
New to this stuff. I just want to know how I can tell tortoise to use my second GPU since that's the one with more ram and power. I tried to look but I couldn't find anyone talking about it.

**Comment by manmay-nakhashi** [comment]
look at CUDA_VISIBLE_DEVICES

**Comment by 1gN0bl3** [comment]
and where is that???

**Comment by manmay-nakhashi** [comment]
It's an environment variable , so you can just Google about that , it's a cuda variable to choose which GPU to select.

**Comment by manmay-nakhashi** [comment]
Using windows or Linux?

**Comment by 1gN0bl3** [comment]
Im using windows. I see the other thread is there a way to make set the variable in conda environment so I don't need to specify every time?

**Comment by manmay-nakhashi** [comment]
To set CUDA_VISIBLE_DEVICES in Windows, you can follow these steps:
Open the Start menu and search for "System."
Click on "System" and then go to "Advanced system settings."
Under "Environment Variables," click on "New."
In the "Variable name" field, type "CUDA_VISIBLE_DEVICES."
In the "Variable value" field, type the number of the GPU that you want to use. For example, to use GPU 0, you would type "0."
Click on "OK."
Once you have set CUDA_VISIBLE_DEVICES, you can then run your application. The application will only be able to see the GPU that you specified.

**Comment by 1gN0bl3** [comment]
I appreciate the help! I managed to get it to work. I'm using a conda env so I did it a little differently. In case anybody else needs it all I did was open the env and then used `conda env config vars set CUDA_VISIBLE_DEVICES=1` after reactivating my env it works fine.

**Comment by xiaoyangnihao** [comment]
> look at CUDA_VISIBLE_DEVICES
@manmay-nakhashi , hi, I am trying to train tortoise-tts's autoregressive module with dlas, can you help if multi-gpus is supported?

**Comment by manmay-nakhashi** [comment]
@xiaoyangnihao it is supported in config you need to modify GPU ids at the top of the yml and then run it with torch.distributed command.
