### ISSUE TITLE
Feature: add random voice

### ISSUE THREAD

**Issue by detkov** [neonbjb/tortoise-tts#7]
I saw that in [silero](https://github.com/snakers4/silero-models#v3) they added random speaker voice to generate TTS, and it sounds quite good. Maybe you can add something similar?

**Comment by neonbjb** [comment]
Hey there - can you be more specific on what you mean? The repo comes packaged with 21 voices. If you were so inclined, you could mix and match them to create thousands of voices.

Are you suggesting that I add a way to auto-pick from one of these voices (or a combination of them) if the user doesn't want to specify it?

**Comment by detkov** [comment]
Sorry, by a random I mean just random unique voice, not one of the 21 voices that are already previded in the repo, but a new one, some random voice (like a random latent vector of voice).

**Comment by neonbjb** [comment]
This is an interesting idea. I'll have to think about it.

**Comment by neonbjb** [comment]
Let's keep this open. I think building something that maps from a random vector to the conditioning vector space has a lot of merit.

**Comment by neonbjb** [comment]
Done! Pass "random" in as the voice. Works pretty well.
