### ISSUE TITLE
Commerical use

### ISSUE THREAD

**Issue by bar9532** [neonbjb/tortoise-tts#785]
Can tortoise-tts be used for commerical uses like monetized videos? In hugging face some of the voices seemed to be from famous people like "freeman" voice which I think is morgan freeman voice if i am not wrong so it will be restricted for commerical uses? If not what voices can be used for commerical use

**Comment by manmay-nakhashi** [comment]
@bar9532 it's Apache 2.0 license so you cna use it without any ristrictions.
