### ISSUE TITLE
I'm getting an error when running locally on Win 11

### ISSUE THREAD

**Issue by JPW0080** [neonbjb/tortoise-tts#8]
I'm getting an error when running locally on Win 11.

OS:  Win 11 21H2 x64
CPU: 8700k
GPU: 3090
RAM: 32GB

Anaconda3 Powershell Prompt:

conda activate chunkmogrify
cd C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\Tortoise-TTS
python do_tts.py --text "I'm going to speak this" --voice freeman --preset fast

TypeError:

Generating autoregressive samples..
  0%|                                                                                            | 0/6 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "do_tts.py", line 32, in <module>
    gen = tts.tts_with_preset(args.text, conds, preset=args.preset, clvp_cvvp_slider=args.voice_diversity_intelligibility_slider)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\Tortoise-TTS\api.py", line 225, in tts_with_preset
    return self.tts(text, voice_samples, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\Tortoise-TTS\api.py", line 301, in tts
    codes = self.autoregressive.inference_speech(conds, text,
  File "C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\Tortoise-TTS\models\autoregressive.py", line 564, in inference_speech
    gen = self.inference_model.generate(inputs, bos_token_id=self.start_mel_token, pad_token_id=self.stop_mel_token, eos_token_id=self.stop_mel_token,
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Anaconda3\envs\chunkmogrify\lib\site-packages\transformers\generation_utils.py", line 931, in generate
    return self.sample(
TypeError: sample() got multiple values for keyword argument 'logits_processor'

conda list:

_tflow_select             2.3.0                       gpu
absl-py                   0.15.0             pyhd3eb1b0_0
addict                    2.4.0                    pypi_0    pypi
aiohttp                   3.8.1            py38h2bbff1b_1
aiosignal                 1.2.0              pyhd3eb1b0_0
albumentations            1.1.0                    pypi_0    pypi
altair                    4.2.0                    pypi_0    pypi
analytics-python          1.4.0                    pypi_0    pypi
antlr4-python3-runtime    4.8                      pypi_0    pypi
anyio                     3.5.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
argon2-cffi               21.3.0             pyhd3eb1b0_0
argon2-cffi-bindings      21.2.0           py38h2bbff1b_0
asgiref                   3.5.0                    pypi_0    pypi
astor                     0.8.1            py38haa95532_0
asttokens                 2.0.5              pyhd3eb1b0_0
astunparse                1.6.3                      py_0
async-timeout             4.0.1              pyhd3eb1b0_0
atomicwrites              1.4.0                    pypi_0    pypi
attrs                     21.4.0             pyhd3eb1b0_0
audioread                 2.1.9                    pypi_0    pypi
av                        9.2.0                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0
backoff                   1.10.0                   pypi_0    pypi
backports-zoneinfo        0.2.1                    pypi_0    pypi
basicsr                   1.3.5                    pypi_0    pypi
bcrypt                    3.2.0                    pypi_0    pypi
beautifulsoup4            4.10.0             pyh06a4308_0
black                     21.4b2                   pypi_0    pypi
blas                      1.0                         mkl
bleach                    4.1.0              pyhd3eb1b0_0
blinker                   1.4              py38haa95532_0
bottleneck                1.3.4            py38h080aedc_0
braceexpand               0.1.7                    pypi_0    pypi
brotli                    1.0.9                ha925a31_2
brotlipy                  0.7.0           py38h2bbff1b_1003
bs4                       4.10.0               hd3eb1b0_0
bzip2                     1.0.8                he774522_0    anaconda
ca-certificates           2022.3.29            haa95532_1
cachetools                4.2.2              pyhd3eb1b0_0
certifi                   2021.10.8        py38haa95532_2
cffi                      1.15.0           py38h2bbff1b_1
chardet                   4.0.0                    pypi_0    pypi
charset-normalizer        2.0.12                   pypi_0    pypi
clean-fid                 0.1.23                   pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
clip                      1.0                      pypi_0    pypi
cloudpickle               2.0.0                    pypi_0    pypi
cmake                     3.22.3                   pypi_0    pypi
colorama                  0.4.4              pyhd3eb1b0_0
commentjson               0.9.0                    pypi_0    pypi
cpython                   0.0.6                    pypi_0    pypi
cryptography              3.4.8            py38h71e12ea_0
cudatoolkit               11.3.1               h59b6b97_2
cvlib                     0.2.7                    pypi_0    pypi
cycler                    0.11.0             pyhd3eb1b0_0
dataclasses               0.8                pyh6d0b6a4_7
debugpy                   1.5.1            py38hd77b12b_0
decorator                 4.4.2                    pypi_0    pypi
deepspeed                 0.3.16                   pypi_0    pypi
defusedxml                0.7.1              pyhd3eb1b0_0
detectron2                0.6                       dev_0    <develop>
dill                      0.3.4              pyhd3eb1b0_0
dlib                      19.23.0                  pypi_0    pypi
dnnlib                    0.0.1                    pypi_0    pypi
docker-pycreds            0.4.0                    pypi_0    pypi
easydict                  1.9                      pypi_0    pypi
einops                    0.4.1                    pypi_0    pypi
entmax                    1.0                      pypi_0    pypi
entrypoints               0.3                      py38_0
executing                 0.8.3              pyhd3eb1b0_0
face-alignment            1.3.5                    pypi_0    pypi
facexlib                  0.2.2                    pypi_0    pypi
fastapi                   0.75.0                   pypi_0    pypi
ffmpeg                    4.2.2                he774522_0
ffmpy                     0.3.0                    pypi_0    pypi
filelock                  3.6.0                    pypi_0    pypi
filetype                  1.0.10                   pypi_0    pypi
filterpy                  1.4.5                    pypi_0    pypi
fire                      0.4.0                    pypi_0    pypi
flask                     1.1.4                    pypi_0    pypi
flask_cors                3.0.10             pyhd3eb1b0_0
flaskwebgui               0.3.5                    pypi_0    pypi
flatbuffers               2.0                      pypi_0    pypi
fonttools                 4.30.0                   pypi_0    pypi
freetype                  2.10.4               hd328e21_0
frozenlist                1.2.0            py38h2bbff1b_0
fsspec                    2022.3.0                 pypi_0    pypi
ftfy                      6.1.1                    pypi_0    pypi
future                    0.18.2                   pypi_0    pypi
fvcore                    0.1.5.post20220305          pypi_0    pypi
gast                      0.4.0              pyhd3eb1b0_0
gcloud                    0.18.3                   pypi_0    pypi
gdown                     4.4.0                    pypi_0    pypi
gfpgan                    1.3.2                    pypi_0    pypi
gitdb                     4.0.9                    pypi_0    pypi
gitpython                 3.1.27                   pypi_0    pypi
glfw                      2.5.1                    pypi_0    pypi
google-api-core           2.7.1                    pypi_0    pypi
google-api-python-client  2.42.0                   pypi_0    pypi
google-auth               1.35.0                   pypi_0    pypi
google-auth-httplib2      0.1.0                    pypi_0    pypi
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0
google-colab              1.0.0              pyh44b312d_0    conda-forge
google-pasta              0.2.0              pyhd3eb1b0_0
googleapis-common-protos  1.56.0                   pypi_0    pypi
gradio                    2.8.13                   pypi_0    pypi
grpcio                    1.42.0           py38hc60d5dd_0
h11                       0.13.0                   pypi_0    pypi
h5py                      2.10.0           py38h5e291fa_0
hdf5                      1.10.4               h7ebc959_0
httplib2                  0.20.4                   pypi_0    pypi
huggingface-hub           0.4.0                    pypi_0    pypi
hydra-core                1.1.1                    pypi_0    pypi
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idna                      2.10                     pypi_0    pypi
imageio                   2.16.1                   pypi_0    pypi
imageio-ffmpeg            0.4.5                    pypi_0    pypi
imgui                     1.4.1                    pypi_0    pypi
importlib-metadata        4.11.3           py38haa95532_0
importlib-resources       5.4.0                    pypi_0    pypi
importlib_metadata        4.11.3               hd3eb1b0_0
imutils                   0.5.4                    pypi_0    pypi
inflect                   5.3.0            py38haa95532_1
iniconfig                 1.1.1                    pypi_0    pypi
insightface               0.2.1                    pypi_0    pypi
intel-openmp              2021.4.0          haa95532_3556
iopath                    0.1.9                    pypi_0    pypi
ipdb                      0.13.9                   pypi_0    pypi
ipykernel                 6.9.1            py38haa95532_0
ipython                   8.2.0            py38haa95532_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.7.0                    pypi_0    pypi
itsdangerous              1.1.0                    pypi_0    pypi
jedi                      0.18.1           py38haa95532_1
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h2bbff1b_0
jsonschema                3.2.0              pyhd3eb1b0_2
jupyter_client            7.1.2              pyhd3eb1b0_0
jupyter_core              4.9.2            py38haa95532_0
jupyterlab-widgets        1.1.0                    pypi_0    pypi
jupyterlab_pygments       0.1.2                      py_0
keras-applications        1.0.8                      py_1
keras-preprocessing       1.1.2              pyhd3eb1b0_0
kiwisolver                1.3.2            py38hd77b12b_0
kornia                    0.6.4                    pypi_0    pypi
lama-cleaner              0.9.3                    pypi_0    pypi
lark-parser               0.7.8                    pypi_0    pypi
libpng                    1.6.37               h2a8f88b_0
libprotobuf               3.19.1               h23ce68f_0
librosa                   0.9.1                    pypi_0    pypi
libtiff                   4.2.0                hd0e1b90_0
libuv                     1.40.0               he774522_0
libwebp                   1.2.2                h2bbff1b_0
linkify-it-py             1.0.3                    pypi_0    pypi
llvmlite                  0.38.0                   pypi_0    pypi
lmdb                      1.3.0                    pypi_0    pypi
loguru                    0.6.0                    pypi_0    pypi
lpips                     0.1.4                    pypi_0    pypi
lz4-c                     1.9.3                h2bbff1b_1
markdown                  3.3.4            py38haa95532_0
markdown-it-py            2.0.1                    pypi_0    pypi
markupsafe                2.0.1            py38h2bbff1b_0
matplotlib                3.5.1            py38haa95532_1
matplotlib-base           3.5.1            py38hd77b12b_1
matplotlib-inline         0.1.2              pyhd3eb1b0_2
mdit-py-plugins           0.3.0                    pypi_0    pypi
mdurl                     0.1.0                    pypi_0    pypi
mistune                   0.8.4           py38he774522_1000
mkl                       2021.4.0           haa95532_640
mkl-service               2.4.0            py38h2bbff1b_0
mkl_fft                   1.3.1            py38h277e83a_0
mkl_random                1.2.2            py38hf11a4ad_0
monotonic                 1.6                      pypi_0    pypi
moviepy                   1.0.3                    pypi_0    pypi
mpi4py                    3.1.3                    pypi_0    pypi
multidict                 5.1.0            py38h2bbff1b_2
munkres                   1.1.4                      py_0
mypy-extensions           0.4.3                    pypi_0    pypi
nbclient                  0.5.11             pyhd3eb1b0_0
nbconvert                 6.1.0            py38haa95532_0
nbformat                  5.1.3              pyhd3eb1b0_0
nest-asyncio              1.5.1              pyhd3eb1b0_0
networkx                  2.7.1                    pypi_0    pypi
ninja                     1.10.2.3                 pypi_0    pypi
notebook                  6.4.8            py38haa95532_0
numba                     0.55.1                   pypi_0    pypi
numexpr                   2.8.1            py38hb80d3ca_0
numpy                     1.20.3                   pypi_0    pypi
numpy-base                1.21.5           py38hc2deb75_0
oauth2client              4.1.3                    pypi_0    pypi
oauthlib                  3.2.0              pyhd3eb1b0_0
omegaconf                 2.1.1                    pypi_0    pypi
onnx                      1.11.0                   pypi_0    pypi
onnxruntime               1.11.0                   pypi_0    pypi
onnxruntime-gpu           1.11.0                   pypi_0    pypi
opencv-python             4.5.5.64                 pypi_0    pypi
opencv-python-headless    4.5.5.64                 pypi_0    pypi
openexr                   1.3.7                    pypi_0    pypi
openssl                   1.1.1n               h2bbff1b_0
opt_einsum                3.3.0              pyhd3eb1b0_1
orjson                    3.6.7                    pypi_0    pypi
packaging                 21.3               pyhd3eb1b0_0
pandas                    1.4.1            py38hd77b12b_1
pandocfilters             1.5.0              pyhd3eb1b0_0
paramiko                  2.10.3                   pypi_0    pypi
parso                     0.8.3              pyhd3eb1b0_0
pathspec                  0.9.0                    pypi_0    pypi
pathtools                 0.1.2                    pypi_0    pypi
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    9.0.1                    pypi_0    pypi
pip                       21.2.2           py38haa95532_0
pluggy                    1.0.0                    pypi_0    pypi
pooch                     1.6.0                    pypi_0    pypi
portalocker               2.4.0                    pypi_0    pypi
portpicker                1.3.1                    py38_0
pprintpp                  0.4.0                    pypi_0    pypi
proglog                   0.1.9                    pypi_0    pypi
progressbar               2.5                      pypi_0    pypi
prometheus_client         0.13.1             pyhd3eb1b0_0
promise                   2.3                      pypi_0    pypi
prompt-toolkit            3.0.28                   pypi_0    pypi
protobuf                  3.19.4                   pypi_0    pypi
psutil                    5.8.0            py38h2bbff1b_1
pudb                      2022.1.1                 pypi_0    pypi
pure_eval                 0.2.2              pyhd3eb1b0_0
py                        1.11.0                   pypi_0    pypi
pyarrow                   7.0.0                    pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0
pyasn1-modules            0.2.8                      py_0
pybind11                  2.9.1            py38hbd9d945_0    conda-forge
pybind11-global           2.9.1            py38hbd9d945_0    conda-forge
pycocotools               2.0.4                    pypi_0    pypi
pycparser                 2.21               pyhd3eb1b0_0
pycryptodome              3.14.1                   pypi_0    pypi
pydantic                  1.9.0                    pypi_0    pypi
pydeck                    0.7.1                    pypi_0    pypi
pydeprecate               0.3.2                    pypi_0    pypi
pydot                     1.4.2                    pypi_0    pypi
pydrive                   1.3.1                    pypi_0    pypi
pydub                     0.25.1                   pypi_0    pypi
pygments                  2.11.2             pyhd3eb1b0_0
pyjwt                     2.1.0            py38haa95532_0
pymcubes                  0.1.2                    pypi_0    pypi
pymongo                   4.0.2                    pypi_0    pypi
pympler                   1.0.1                    pypi_0    pypi
pynacl                    1.5.0                    pypi_0    pypi
pyopengl                  3.1.1a1          py38haa95532_0
pyopenssl                 21.0.0             pyhd3eb1b0_1
pyparsing                 3.0.4              pyhd3eb1b0_0
pyqt                      5.9.2            py38hd77b12b_6
pyqt5                     5.15.6                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.1                   pypi_0    pypi
pyrallis                  0.3.1                    pypi_0    pypi
pyreadline                2.1                      py38_1
pyrsistent                0.18.0           py38h196d8e1_0
pysimplegui               4.59.0                   pypi_0    pypi
pysocks                   1.7.1            py38haa95532_0
pyspng                    0.1.0                    pypi_0    pypi
pytest                    7.1.1                    pypi_0    pypi
python                    3.8.12               h6244533_0
python-dateutil           2.8.2              pyhd3eb1b0_0
python-multipart          0.0.5                    pypi_0    pypi
python_abi                3.8                      2_cp38    conda-forge
pytorch                   1.11.0          py3.8_cuda11.3_cudnn8_0    pytorch
pytorch-lightning         1.6.0                    pypi_0    pypi
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2022.1                   pypi_0    pypi
pytz-deprecation-shim     0.1.0.post0              pypi_0    pypi
pywavelets                1.3.0                    pypi_0    pypi
pywin32                   303                      pypi_0    pypi
pywinpty                  2.0.5                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
pyzmq                     22.3.0           py38hd77b12b_2
qt                        5.9.7            vc14h73c81de_0
qudida                    0.0.4                    pypi_0    pypi
realesrgan                0.2.4.0                  pypi_0    pypi
regex                     2022.3.2                 pypi_0    pypi
requests                  2.25.1                   pypi_0    pypi
requests-oauthlib         1.3.0                      py_0
resampy                   0.2.2                    pypi_0    pypi
rotary-embedding-torch    0.1.5                    pypi_0    pypi
rsa                       4.7.2              pyhd3eb1b0_1
sacremoses                0.0.49                   pypi_0    pypi
samplerate                0.1.0                    pypi_0    pypi
scikit-image              0.19.2                   pypi_0    pypi
scikit-learn              1.0.2                    pypi_0    pypi
scipy                     1.8.0                    pypi_0    pypi
seaborn                   0.11.2             pyhd3eb1b0_0
semver                    2.13.0                   pypi_0    pypi
send2trash                1.8.0              pyhd3eb1b0_1
sentry-sdk                1.5.7                    pypi_0    pypi
setproctitle              1.2.2                    pypi_0    pypi
setuptools                58.0.4           py38haa95532_0
shortuuid                 1.0.8                    pypi_0    pypi
sip                       4.19.13          py38hd77b12b_0
six                       1.16.0             pyhd3eb1b0_1
smmap                     5.0.0                    pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
soundfile                 0.10.3.post1             pypi_0    pypi
soundstretch              1.2                      pypi_0    pypi
soupsieve                 2.3.1              pyhd3eb1b0_0
sqlite                    3.38.2               h2bbff1b_0
stack_data                0.2.0              pyhd3eb1b0_0
starlette                 0.17.1                   pypi_0    pypi
streamlit                 1.8.1                    pypi_0    pypi
submitit                  1.4.1                    pypi_0    pypi
tabulate                  0.8.9                    pypi_0    pypi
taming-transformers       0.0.1                    pypi_0    pypi
tb-nightly                2.9.0a20220402           pypi_0    pypi
tensorboard               2.4.0              pyhc547734_0
tensorboard-data-server   0.6.1                    pypi_0    pypi
tensorboard-plugin-wit    1.6.0                      py_0
tensorboardx              1.8                      pypi_0    pypi
tensorflow                2.3.0           mkl_py38h8557ec7_0
tensorflow-base           2.3.0           eigen_py38h75a453f_0
tensorflow-estimator      2.6.0              pyh7b7c402_0
tensorflow-gpu            2.3.0                he13fc11_0
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.13.3                   pypi_0    pypi
test-tube                 0.7.5                    pypi_0    pypi
testpath                  0.5.0              pyhd3eb1b0_0
threadpoolctl             3.1.0                    pypi_0    pypi
tifffile                  2022.2.9                 pypi_0    pypi
timm                      0.5.4                    pypi_0    pypi
tk                        8.6.10               he774522_0    anaconda
tokenizers                0.10.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     2.0.1                    pypi_0    pypi
toolz                     0.11.2                   pypi_0    pypi
torch                     1.11.0                   pypi_0    pypi
torch-fidelity            0.3.0                    pypi_0    pypi
torchaudio                0.11.0               py38_cu113    pytorch
torchmetrics              0.7.3                    pypi_0    pypi
torchtyping               0.1.4                    pypi_0    pypi
torchvision               0.12.0                   pypi_0    pypi
tornado                   6.1              py38h2bbff1b_0
tqdm                      4.64.0                   pypi_0    pypi
traitlets                 5.1.1              pyhd3eb1b0_0
transformers              4.3.1                    pypi_0    pypi
trimesh                   3.10.5                   pypi_0    pypi
typeguard                 2.13.3                   pypi_0    pypi
typing-extensions         4.1.1                hd3eb1b0_0
typing-inspect            0.7.1                    pypi_0    pypi
typing_extensions         4.1.1              pyh06a4308_0
tzdata                    2022.1                   pypi_0    pypi
tzlocal                   4.2                      pypi_0    pypi
uc-micro-py               1.0.1                    pypi_0    pypi
unidecode                 1.2.0              pyhd3eb1b0_0
unzip                     1.0.0                    pypi_0    pypi
uritemplate               4.1.1                    pypi_0    pypi
urllib3                   1.26.8             pyhd3eb1b0_0
urwid                     2.1.2                    pypi_0    pypi
urwid-readline            0.13                     pypi_0    pypi
uvicorn                   0.17.6                   pypi_0    pypi
validators                0.18.2                   pypi_0    pypi
vc                        14.2                 h21ff451_1
vs2015_runtime            14.27.29016          h5e58377_2
wandb                     0.12.11                  pypi_0    pypi
watchdog                  2.1.7                    pypi_0    pypi
wcwidth                   0.2.5              pyhd3eb1b0_0
webdataset                0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
werkzeug                  1.0.1                    pypi_0    pypi
wget                      3.2                      pypi_0    pypi
wheel                     0.37.1             pyhd3eb1b0_0
whichcraft                0.6.1                    pypi_0    pypi
widgetsnbextension        3.6.0                    pypi_0    pypi
win32-setctime            1.1.0                    pypi_0    pypi
win_inet_pton             1.1.0            py38haa95532_0
wincertstore              0.2              py38haa95532_2
winpty                    0.4.3                         4
wldhx-yadisk-direct       0.0.6                    pypi_0    pypi
wrapt                     1.13.3           py38h2bbff1b_2
xz                        5.2.5                h62dcd97_0
yacs                      0.1.8                    pypi_0    pypi
yaml                      0.2.5                he774522_0
yapf                      0.32.0                   pypi_0    pypi
yarl                      1.6.3            py38h2bbff1b_0
yaspin                    2.1.0                    pypi_0    pypi
zipp                      3.7.0              pyhd3eb1b0_0
zlib                      1.2.11               hbd8134f_5
zstd                      1.4.9                h19a0ad4_0

**Comment by neonbjb** [comment]
Hey, try updating your transformers library.

This works on windows 11 for sure.

**Comment by JPW0080** [comment]
Thanks, the below has solved it:

Anaconda3 Command Prompt:

conda activate chunkmogrify

cd C:\Anaconda3\envs\chunkmogrify\Lib\site-packages\Tortoise-TTS

conda install -c conda-forge transformers
