### ISSUE TITLE
need more help about diffusion finetune

### ISSUE THREAD

**Issue by JohnHerry** [neonbjb/tortoise-tts#801]
Hi, neonbjb
    I am going into the fine-tune step of DDPM.  I have some confussion about what is the "AR activations".  I have TWO different guesses here.  The First,  I put the [text tokens, mel tokens]  list into the AR model, and get the GPT output hidden_states, then split out the part correspond to the "mel tokens" from the hidden_states, that is the "AR activations".  The Second,  I put the [text tokens] into the AR model, and predic for "len(mel tokesn)" iterations. each time I get the last tensor of GPT hidden_states.  at last, I concatenate those tensors into one, which will be used as the "AR activations".  which one is the right?

**Comment by hoyden** [comment]
The first one. Use teacher forcing forward to get AR activations

**Comment by JohnHerry** [comment]
Thank you very much!
