### ISSUE TITLE
VQ-VAE training details

### ISSUE THREAD

**Issue by ioneuk** [neonbjb/tortoise-tts#92]
Hello. Your work is absolutely great. One of the best TTS that I've ever seen.
I am trying to understand your work conceptually. My questions are related to VQ-VAE  pretraining on the speech data:
1. I am struggling to understand whether the Diffusion model was trained as a VQ-VAE decoder or VQ-VAE decoder and the diffusion model are different models trained separately.
2. Was VQ-VAE conditioned on text and conditioning latent?
3. It would be great to know the architecture/losses and other training details of the VQ-VAE model you used. Are they the same as described [here](https://arxiv.org/abs/1711.00937) ?

**Comment by QajikHakobyan** [comment]
Hi @neonbjb,

First off, thank you for the incredible work on this project! I have a quick question regarding the Mel Spectrograms used in the discrete autoencoder and diffusion training. Could you please clarify what type of normalization is applied to the Mel Spectrograms during these stages?

Thanks in advance!
