### ISSUE TITLE
Question!!!

### ISSUE THREAD

**Issue by DillFrescott** [neonbjb/tortoise-tts#99]
I love this! Is there a way to do voice conversion instead of a text to speech?

**Comment by neonbjb** [comment]
Sorry, not with this model as it currently stands.

**Comment by DillFrescott** [comment]
Okay. Thank you!

**Comment by dillfrescott** [comment]
@neonbjb any progress on this since June?

**Comment by neonbjb** [comment]
I am not working on this actively, apologies.

**Comment by dillfrescott** [comment]
Oh no issue at all! Was just curious!
